# create index

In [1]:
import numpy as np
import random
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('Studentsperformance.csv')

In [3]:
# create non repetitive values for the index
new_index = np.arange(0,1000)

In [4]:
# shuffling the indexes
random.shuffle(new_index)

In [5]:
# create a new column with  new index 
df_exams['new_index'] = new_index
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,491
1,female,group C,some college,standard,completed,69,90,88,964
2,female,group B,master's degree,standard,none,90,95,93,563
3,male,group A,associate's degree,free/reduced,none,47,57,44,379
4,male,group C,some college,standard,none,76,78,75,918

# set index

inplace=False (default)
→ returns a new sorted/modified DataFrame
→ original DataFrame stays unchanged
inplace=True
→ modifies the original DataFrame directly
→ returns None (this is important!)
When to use it?
+ Use inplace=True → when you don’t need the original data anymore
+ Otherwise → safer to keep default (False)
###### Commom mistake
+  df = df.sort_values(by="age", inplace=True)

👉 This makes df = None ❌
(because the method returns nothing)

In [6]:
# set new index column as index  # inplace : bool, default False
# Whether to modify the DataFrame rather than creating a new one.

df_exams.set_index('new_index', inplace=True) 
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
491,female,group B,bachelor's degree,standard,none,72,72,74
964,female,group C,some college,standard,completed,69,90,88
563,female,group B,master's degree,standard,none,90,95,93
379,male,group A,associate's degree,free/reduced,none,47,57,44
918,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
72,female,group E,master's degree,standard,completed,88,99,95
309,male,group C,high school,free/reduced,none,62,55,55
824,female,group C,high school,free/reduced,completed,59,71,65
690,female,group D,some college,standard,completed,68,78,77
933,female,group D,some college,free/reduced,none,77,86,86

In [7]:
# sort descending by index
df_exams.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group D,some high school,standard,none,59,58,59
998,female,group D,associate's degree,free/reduced,none,52,59,56
997,male,group D,master's degree,standard,none,80,80,72
996,female,group B,associate's degree,free/reduced,none,46,61,55
995,male,group C,high school,free/reduced,none,27,34,36
...,...,...,...,...,...,...,...,...
4,male,group D,some high school,standard,none,75,74,69
3,male,group A,some college,standard,none,53,43,43
2,male,group C,high school,standard,none,70,56,51
1,female,group D,some college,standard,none,69,77,77
0,female,group D,high school,standard,completed,57,58,64

In [8]:
# sort descending by index
df_exams.sort_index(ascending=False, inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group D,some high school,standard,none,59,58,59
998,female,group D,associate's degree,free/reduced,none,52,59,56
997,male,group D,master's degree,standard,none,80,80,72
996,female,group B,associate's degree,free/reduced,none,46,61,55
995,male,group C,high school,free/reduced,none,27,34,36
...,...,...,...,...,...,...,...,...
4,male,group D,some high school,standard,none,75,74,69
3,male,group A,some college,standard,none,53,43,43
2,male,group C,high school,standard,none,70,56,51
1,female,group D,some college,standard,none,69,77,77
0,female,group D,high school,standard,completed,57,58,64

# Rename Column

In [9]:
# rename column and overwrite the existing column
df_exams.rename(columns={'gender': 'Gender'}, inplace=True)