In [2]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv('Studentsperformance.csv')

In [4]:
# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1  Selecting two or more columns

In [5]:
df_exams[['gender', 'math score']]   # selecting two columns from the dataframe

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [6]:
# check out the data type of te selection
type(df_exams[['gender', 'math score']])

pandas.DataFrame

In [7]:
# select 2 or more columns using [[]]

# 1 Adding a new Column to dataframe

### 1.1 Adding a new column  with a scalar value

In [8]:
# adding new colum to dataframe
df_exams ['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

### 1.2  Adding a new column with an array


The dataframe has 1000 rows , so we need to create an array with 1000 elements

In [9]:
import numpy as np

In [10]:
# create an array of 1000 elements
language_score = np.arange(0,1000)

In [11]:
 #  lent of the array
len(language_score)

1000

In [12]:
# adding a new column to dataframe with an array
df_exams['language score']  = language_score

In [13]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [14]:
# create array of  random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size = 1000)
len(language_score)

1000

In [15]:
# min value inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

np.int32(99)

In [16]:
# adding a new column to dataframe with an array
df_exams['language score']  = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,17
1,female,group C,some college,standard,completed,69,90,88,46
2,female,group B,master's degree,standard,none,90,95,93,90
3,male,group A,associate's degree,free/reduced,none,47,57,44,14
4,male,group C,some college,standard,none,76,78,75,97
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,43
996,male,group C,high school,free/reduced,none,62,55,55,88
997,female,group C,high school,free/reduced,completed,59,71,65,1
998,female,group D,some college,standard,completed,68,78,77,55
999,female,group D,some college,free/reduced,none,77,86,86,84

In [17]:
# create random float numbers between 1 and 100
np.random.uniform(1,100, size =100)

array([60.41216487, 46.19337523, 17.55357537, 10.36081636,  2.48622695,
       81.77011889,  7.62271326, 75.20318744, 64.35063246, 67.03601201,
       99.71551495, 25.23801002, 11.19616241, 93.6493623 , 68.30716004,
       58.39955249, 93.65278036, 32.89818908, 31.41387691, 98.73149346,
       23.87313552, 60.52477309, 14.35600629, 13.26630775, 81.88917156,
       39.00551356, 88.36627705, 99.08853754, 49.64293846, 29.90191064,
       66.84912288, 54.25130552, 64.60297293, 67.25344054, 22.01910556,
       48.1869714 , 23.23032275, 17.37070808, 56.44003755,  9.28415655,
       65.96590792, 25.57423627, 49.1352376 , 73.99224986, 58.35333187,
       95.44411257,  3.67852967,  4.118323  , 63.3431176 , 85.15155546,
       27.65698509, 60.07397614, 37.6718403 , 45.22137863, 14.59616736,
        9.7951647 , 50.97138666, 69.75957719, 30.96653031, 78.32478767,
       68.84178741, 13.13204421, 52.06759204, 90.94043602, 24.4592626 ,
       59.13025279, 93.88368743, 26.94642589, 56.42198102,  2.42633104,
       81.84105678, 17.70532462, 27.47523805, 39.59284013, 52.96943886,
       39.85231179, 63.19069386, 69.52007739, 84.92258625, 96.10160523,
       28.84396009, 12.7164797 , 31.94443574, 24.2310466 , 46.18144161,
       28.64189581, 12.34345677, 22.58339085, 59.9205675 , 87.78622253,
       98.12139057, 98.11634585, 67.57553254, 15.31206696, 52.36628893,
       27.353222  , 56.93704117, 30.40495586,  6.44027652, 34.89301059])

### 1.2 assign()

When  to use assign?
  
  - Add multiple columns in a single line of code.
  - when  you need to overwrite  the values of an existing columns(best practice)

 it returns a new object (a copy) with all the original columns in addition to the new ones

In [18]:
import numpy as np

In [19]:
#create random numbers for our new score  columns
score1 = np.random.randint(1, 100, size =1000)
score2 = np.random.randint(1, 100, size =1000)

In [20]:
# create a series using the random numbers
series1 =pd.Series(score1, index=np.arange(0,  1000))
series2 =pd.Series(score2, index=np.arange(0,  1000))

In [21]:
series1, series2

(0      64
 1      46
 2      95
 3      50
 4      88
        ..
 995    41
 996    25
 997    25
 998    12
 999     4
 Length: 1000, dtype: int32,
 0      22
 1       8
 2      43
 3      62
 4      30
        ..
 995     9
 996    53
 997    10
 998    17
 999    12
 Length: 1000, dtype: int32)

In [22]:
# using assign () to add multiple columns
df_exams= df_exams.assign(score1=series1,  score2=series2)

In [23]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,17,64,22
1,female,group C,some college,standard,completed,69,90,88,46,46,8
2,female,group B,master's degree,standard,none,90,95,93,90,95,43
3,male,group A,associate's degree,free/reduced,none,47,57,44,14,50,62
4,male,group C,some college,standard,none,76,78,75,97,88,30
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,43,41,9
996,male,group C,high school,free/reduced,none,62,55,55,88,25,53
997,female,group C,high school,free/reduced,completed,59,71,65,1,25,10
998,female,group D,some college,standard,completed,68,78,77,55,12,17
999,female,group D,some college,free/reduced,none,77,86,86,84,4,12

###  1.2 insert()

Inserts a new column at a specific position or index.

In [24]:
#  using index()  to add a column at a specific position , this works direct without =
df_exams.insert(1, 'test' , series1)

In [25]:
#  show the dataframe
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,64,group B,bachelor's degree,standard,none,72,72,74,17,64,22
1,female,46,group C,some college,standard,completed,69,90,88,46,46,8
2,female,95,group B,master's degree,standard,none,90,95,93,90,95,43
3,male,50,group A,associate's degree,free/reduced,none,47,57,44,14,50,62
4,male,88,group C,some college,standard,none,76,78,75,97,88,30
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,41,group E,master's degree,standard,completed,88,99,95,43,41,9
996,male,25,group C,high school,free/reduced,none,62,55,55,88,25,53
997,female,25,group C,high school,free/reduced,completed,59,71,65,1,25,10
998,female,12,group D,some college,standard,completed,68,78,77,55,12,17
999,female,4,group D,some college,free/reduced,none,77,86,86,84,4,12

# Understanding concat() - Combining DataFrames
concat() combines multiple DataFrames into one. The direction depends on the axis parameter:

### Vertical Concatenation (axis=0 or axis='index')
Stacks DataFrames on top of each other — adds rows

In [26]:
import pandas as pd

# Create sample dataframes
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df2 = pd.DataFrame({'Name': ['Charlie', 'Diana'], 'Age': [35, 28]})

print("df1:")
print(df1)
print("\ndf2:")
print(df2)

# Vertical concatenation (stack them)
result = pd.concat([df1, df2], axis=0)
print("\nVertical concat (axis=0):")
print(result)

df1:
    Name  Age
0  Alice   25
1    Bob   30

df2:
      Name  Age
0  Charlie   35
1    Diana   28

Vertical concat (axis=0):
      Name  Age
0    Alice   25
1      Bob   30
0  Charlie   35
1    Diana   28

### Horizontal Concatenation (axis=1 or axis='columns')
Places DataFrames side by side — adds columns

In [27]:
# Create sample dataframes
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df3 = pd.DataFrame({'City': ['NYC', 'LA'], 'Salary': [50000, 60000]})

print("df1:")
print(df1)
print("\ndf3:")
print(df3)

# Horizontal concatenation (side by side)
result = pd.concat([df1, df3], axis=1)
print("\nHorizontal concat (axis=1):")
print(result)

df1:
    Name  Age
0  Alice   25
1    Bob   30

df3:
  City  Salary
0  NYC   50000
1   LA   60000

Horizontal concat (axis=1):
    Name  Age City  Salary
0  Alice   25  NYC   50000
1    Bob   30   LA   60000

Here's the samples breakdown  with **pandas**:

---

## Attributes (no parentheses)
```python
df.shape          # (rows, columns) as a tuple
df.columns        # list of column names
df.dtypes         # data type of each column
df.index          # row index
df.values         # data as a numpy array
df.size           # total number of elements
df.ndim           # number of dimensions (always 2)
df.empty          # True/False if df has no data
df.T              # transpose (also an attribute)
```

---

## Methods (with parentheses)

**Exploring**
```python
df.head()
df.tail()
df.describe()
df.info()
df.sample(5)
df.count()
```

**Selecting & Filtering**
```python
df[["col1", "col2"]]
df.filter(items=["col1", "col2"])
df.loc[0:5]
df.iloc[0:5]
df.query("age > 30")
```

**Cleaning**
```python
df.dropna()
df.fillna(0)
df.drop("col1", axis=1)
df.drop_duplicates()
df.rename(columns={"old": "new"})
df.reset_index()
df.set_index("col1")
```

**Transforming**
```python
df.assign(new_col=df.salary * 1.1)
df.astype({"age": int})
df.sort_values("age", ascending=False)
df.sort_index()
df.apply(lambda x: x * 2)
df.map(str)
df.replace(0, 99)
```

**Aggregating**
```python
df.groupby("dept")["salary"].mean()
df.sum()
df.mean()
df.median()
df.min()
df.max()
df.std()
df.var()
df.corr()
df.value_counts()
```

**Joining & Reshaping**
```python
df.merge(other_df, on="id", how="left")
df.concat([df1, df2])
df.join(other_df)
df.melt()                # wide to long
df.pivot()               # long to wide
df.pivot_table()
df.stack()
df.unstack()
df.explode("col")
```

**Exporting**
```python
df.to_csv("output.csv")
df.to_json("output.json")
df.to_excel("output.xlsx")
df.to_sql("table", connection)
df.to_dict()
df.to_numpy()
```

---

## Side by side reminder

| | Attributes | Methods |
|---|---|---|
| **Parentheses** | No `()` | Yes `()` |
| **Examples** | `df.shape`, `df.dtypes`, `df.columns` | `df.head()`, `df.describe()`, `df.dropna()` |

Pandas is still the most widely taught and used, so these are the ones you'll see most often in data science courses and tutorials.