In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('Studentsperformance.csv')

In [3]:
# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1  Selecting two or more columns

In [4]:
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [5]:
# check out the data type of te selection
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [6]:
# select 2 or more columns using [[]]

# 1 Adding a new Column to dataframe

### 1.1 Adding a new column  with a scalar value

In [7]:
# adding new colum to dataframe
df_exams ['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

### 1.2  Adding a new column with an array


The dataframe has 1000 rows , so we need to create an array with 1000 elements

In [8]:
import numpy as np

In [9]:
# create an array of 1000 elements
language_score = np.arange(0,1000)

In [10]:
 #  lent of the array
len(language_score)

1000

In [11]:
# adding a new column to dataframe with an array
df_exams['language score']  = language_score

In [12]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [13]:
# create array of  random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size = 1000)
len(language_score)

1000

In [14]:
# min value inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

np.int32(99)

In [15]:
# adding a new column to dataframe with an array
df_exams['language score']  = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,18
1,female,group C,some college,standard,completed,69,90,88,29
2,female,group B,master's degree,standard,none,90,95,93,10
3,male,group A,associate's degree,free/reduced,none,47,57,44,50
4,male,group C,some college,standard,none,76,78,75,80
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,30
996,male,group C,high school,free/reduced,none,62,55,55,2
997,female,group C,high school,free/reduced,completed,59,71,65,46
998,female,group D,some college,standard,completed,68,78,77,56
999,female,group D,some college,free/reduced,none,77,86,86,78

In [16]:
# create random float numbers between 1 and 100
np.random.uniform(1,100, size =100)

array([98.45944679, 31.96918118, 82.40801734,  5.48474667, 10.11987184,
       75.20826719, 48.63963019, 34.207681  , 74.16601543,  1.8736913 ,
       62.43204334, 93.46287383, 67.99658787, 53.70708647, 91.21763437,
       95.03843245, 71.95271086, 96.40616268, 77.05341435, 22.49540063,
       73.14462027, 22.99688175, 88.02401408, 53.25527681, 43.0668035 ,
       50.24549922,  8.54465485, 85.39293632, 31.72073662, 40.81931652,
        2.39520133, 38.940288  , 71.12142673, 54.93543403,  8.67879971,
       74.58970928, 18.49781079, 91.97874924,  8.02023186, 25.00138727,
       42.42444434, 96.69474029, 14.74713651, 39.17417056, 61.22792273,
       37.98737937, 85.66289302, 50.75975207, 17.96145186, 27.05022965,
       33.59223844, 72.38548585, 86.20504335, 90.60060717, 21.89684924,
       22.34982178, 67.28636309, 54.63682852, 33.84757824, 45.03412345,
       62.51328464,  4.19527307, 96.74763725, 84.17447731, 99.59439318,
       19.22094195, 63.87380756, 37.26057517, 99.92979679, 70.99663222,
       32.00619886,  9.48955374, 29.80569761, 17.86279185, 59.68493135,
       36.05414075, 90.78373291, 66.64065421, 13.07265511, 58.10370765,
       73.05012725, 59.21944662, 96.37049089, 90.23928123, 59.21549758,
       70.30564396, 36.23731564, 94.42323637, 96.26551164, 51.70140649,
       11.22797973, 23.24514598, 42.95395661, 26.42322654, 90.69887537,
       50.4765462 , 88.32771815, 57.18616399, 84.76215381, 41.54497029])

### 1.2 assign()

When  to use assign?
  
  - Add multiple columns in a single line of code.
  - when  you need to overwrite  the values of an existing columns(best practice)

 it returns a new object (a copy) with all the original columns in addition to the new ones

In [17]:
import numpy as np

In [18]:
#create random numbers for our new score  columns
score1 = np.random.randint(1, 100, size =1000)
score2 = np.random.randint(1, 100, size =1000)

In [19]:
# create a series using the random numbers
series1 =pd.Series(score1, index=np.arange(0,  1000))
series2 =pd.Series(score2, index=np.arange(0,  1000))

In [20]:
series1, series2

(0      69
 1      17
 2      62
 3      25
 4      18
        ..
 995    71
 996    50
 997    73
 998    27
 999    82
 Length: 1000, dtype: int32,
 0      83
 1      26
 2      13
 3      78
 4      66
        ..
 995    15
 996    12
 997    91
 998    34
 999    14
 Length: 1000, dtype: int32)

In [21]:
# using assign () to add multiple columns
df_exams= df_exams.assign(score1=series1,  score2=series2)

In [22]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,18,69,83
1,female,group C,some college,standard,completed,69,90,88,29,17,26
2,female,group B,master's degree,standard,none,90,95,93,10,62,13
3,male,group A,associate's degree,free/reduced,none,47,57,44,50,25,78
4,male,group C,some college,standard,none,76,78,75,80,18,66
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,30,71,15
996,male,group C,high school,free/reduced,none,62,55,55,2,50,12
997,female,group C,high school,free/reduced,completed,59,71,65,46,73,91
998,female,group D,some college,standard,completed,68,78,77,56,27,34
999,female,group D,some college,free/reduced,none,77,86,86,78,82,14

###  1.2 insert()

Inserts a new column at a specific position or index.

In [23]:
#  using index()  to add a column at a specific position , this works direct without =
df_exams.insert(1, 'test' , series1)

In [24]:
#  show the dataframe
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,69,group B,bachelor's degree,standard,none,72,72,74,18,69,83
1,female,17,group C,some college,standard,completed,69,90,88,29,17,26
2,female,62,group B,master's degree,standard,none,90,95,93,10,62,13
3,male,25,group A,associate's degree,free/reduced,none,47,57,44,50,25,78
4,male,18,group C,some college,standard,none,76,78,75,80,18,66
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,71,group E,master's degree,standard,completed,88,99,95,30,71,15
996,male,50,group C,high school,free/reduced,none,62,55,55,2,50,12
997,female,73,group C,high school,free/reduced,completed,59,71,65,46,73,91
998,female,27,group D,some college,standard,completed,68,78,77,56,27,34
999,female,82,group D,some college,free/reduced,none,77,86,86,78,82,14

# Understanding concat() - Combining DataFrames
concat() combines multiple DataFrames into one. The direction depends on the axis parameter:

### Vertical Concatenation (axis=0 or axis='index')
Stacks DataFrames on top of each other — adds rows

In [25]:
import pandas as pd

# Create sample dataframes
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df2 = pd.DataFrame({'Name': ['Charlie', 'Diana'], 'Age': [35, 28]})

print("df1:")
print(df1)
print("\ndf2:")
print(df2)

# Vertical concatenation (stack them)
result = pd.concat([df1, df2], axis=0)
print("\nVertical concat (axis=0):")
print(result)

df1:
    Name  Age
0  Alice   25
1    Bob   30

df2:
      Name  Age
0  Charlie   35
1    Diana   28

Vertical concat (axis=0):
      Name  Age
0    Alice   25
1      Bob   30
0  Charlie   35
1    Diana   28

### Horizontal Concatenation (axis=1 or axis='columns')
Places DataFrames side by side — adds columns

In [26]:
# Create sample dataframes
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df3 = pd.DataFrame({'City': ['NYC', 'LA'], 'Salary': [50000, 60000]})

print("df1:")
print(df1)
print("\ndf3:")
print(df3)

# Horizontal concatenation (side by side)
result = pd.concat([df1, df3], axis=1)
print("\nHorizontal concat (axis=1):")
print(result)

df1:
    Name  Age
0  Alice   25
1    Bob   30

df3:
  City  Salary
0  NYC   50000
1   LA   60000

Horizontal concat (axis=1):
    Name  Age City  Salary
0  Alice   25  NYC   50000
1    Bob   30   LA   60000

Here's the samples breakdown  with **pandas**:

---

## Attributes (no parentheses)
```python
df.shape          # (rows, columns) as a tuple
df.columns        # list of column names
df.dtypes         # data type of each column
df.index          # row index
df.values         # data as a numpy array
df.size           # total number of elements
df.ndim           # number of dimensions (always 2)
df.empty          # True/False if df has no data
df.T              # transpose (also an attribute)
```

---

## Methods (with parentheses)

**Exploring**
```python
df.head()
df.tail()
df.describe()
df.info()
df.sample(5)
df.count()
```

**Selecting & Filtering**
```python
df[["col1", "col2"]]
df.filter(items=["col1", "col2"])
df.loc[0:5]
df.iloc[0:5]
df.query("age > 30")
```

**Cleaning**
```python
df.dropna()
df.fillna(0)
df.drop("col1", axis=1)
df.drop_duplicates()
df.rename(columns={"old": "new"})
df.reset_index()
df.set_index("col1")
```

**Transforming**
```python
df.assign(new_col=df.salary * 1.1)
df.astype({"age": int})
df.sort_values("age", ascending=False)
df.sort_index()
df.apply(lambda x: x * 2)
df.map(str)
df.replace(0, 99)
```

**Aggregating**
```python
df.groupby("dept")["salary"].mean()
df.sum()
df.mean()
df.median()
df.min()
df.max()
df.std()
df.var()
df.corr()
df.value_counts()
```

**Joining & Reshaping**
```python
df.merge(other_df, on="id", how="left")
df.concat([df1, df2])
df.join(other_df)
df.melt()                # wide to long
df.pivot()               # long to wide
df.pivot_table()
df.stack()
df.unstack()
df.explode("col")
```

**Exporting**
```python
df.to_csv("output.csv")
df.to_json("output.json")
df.to_excel("output.xlsx")
df.to_sql("table", connection)
df.to_dict()
df.to_numpy()
```

---

## Side by side reminder

| | Attributes | Methods |
|---|---|---|
| **Parentheses** | No `()` | Yes `()` |
| **Examples** | `df.shape`, `df.dtypes`, `df.columns` | `df.head()`, `df.describe()`, `df.dropna()` |

Pandas is still the most widely taught and used, so these are the ones you'll see most often in data science courses and tutorials.