In [1]:
import pandas as pd
# Set pandas display options to truncate dataframes
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', None)

# 1 Read a .csv from a URL with Pandas

target website: https://www.football-data.co.uk/data.php

In [2]:
# reading 1 csv file from the website and serving it to a variable
url = "https://www.football-data.co.uk/mmz4281/2526/E0.csv"
df_pr2526 = pd.read_csv(url)

In [3]:
print(df_pr2526)

    Div        Date   Time        HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0    E0  15/08/2025  20:00       Liverpool  Bournemouth     4     2   H     1
1    E0  16/08/2025  12:30     Aston Villa    Newcastle     0     0   D     0
2    E0  16/08/2025  15:00        Brighton       Fulham     1     1   D     0
3    E0  16/08/2025  15:00      Sunderland     West Ham     3     0   H     0
4    E0  16/08/2025  15:00       Tottenham      Burnley     3     0   H     1
..   ..         ...    ...             ...          ...   ...   ...  ..   ...
313  E0  11/04/2026  17:30       Liverpool       Fulham     2     0   H     2
314  E0  12/04/2026  14:00  Crystal Palace    Newcastle     2     1   H     0
315  E0  12/04/2026  14:00   Nott'm Forest  Aston Villa     1     1   D     1
316  E0  12/04/2026  14:00      Sunderland    Tottenham     1     0   H     0
317  E0  12/04/2026  16:30         Chelsea     Man City     0     3   A     0

     HTAG HTR      Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  \
0       0   H     A Taylor  19  10   10    3   7  10   6   7   1   2   0   0
1       0   D     C Pawson   3  16    3    3  13  11   3   6   1   1   1   0
2       0   D    S Barrott  10   7    4    2  16  15   4   3   3   3   0   0
3       0   D      R Jones  10  12    5    4   8  10   5   7   0   1   0   0
4       0   H     M Oliver  16  14    6    4  14   8   6   5   0   0   0   0
..    ...  ..          ...  ..  ..  ...  ...  ..  ..  ..  ..  ..  ..  ..  ..
313     0   H     A Taylor  18  19    5    4  10   4   6   9   0   0   0   0
314     1   A     A Madley  11   7    5    3  17  12   2   4   0   3   0   0
315     1   D  M Salisbury  15  12    4    5  15  10   7   3   2   2   0   0
316     0   D      R Jones  13  11    2    7  14  15   2   6   3   3   0   0
317     0   D   C Kavanagh  12  18    3    8  10  14   4  12   3   1   0   0

     B365H  B365D  B365A  BFDH  BFDD  BFDA  BMGMH  BMGMD  BMGMA   BVH  BVD  \
0     1.30   6.00   8.50  1.30  6.00  9.50   1.29   6.50   9.00  1.30  6.0
1     2.25   3.50   2.90  2.25  3.75  3.10   2.38   3.55   2.95  2.30  3.5
2     1.91   3.60   4.00  1.95  3.75  4.00   1.92   3.65   4.00  1.91  3.6
3     3.25   3.40   2.25  3.20  3.50  2.30   3.25   3.50   2.25  3.20  3.3
4     1.38   4.75   8.50  1.36  5.00  9.50   1.37   5.00   9.00  1.33  4.6
..     ...    ...    ...   ...   ...   ...    ...    ...    ...   ...  ...
313   1.65   4.20   4.75  1.62  4.20  5.00   1.58   4.30   5.00  1.65  4.2
314   3.00   3.60   2.20  3.10  3.60  2.25   3.15   3.35   2.23  3.10  3.6
315   2.63   3.30   2.70  2.60  3.50  2.63   2.60   3.30   2.65  2.63  3.4
316   2.70   3.20   2.70  2.63  3.50  2.63   2.63   3.25   2.65  2.63  3.4
317   3.10   3.80   2.15  3.10  4.00  2.10   3.25   3.65   2.05  3.00  3.7

      BVA   BWH  BWD   BWA   CLH   CLD   CLA   LBH   LBD   LBA   PSH   PSD  \
0    8.50  1.32  5.5  7.50  1.33  5.75  8.00  1.33  5.75  7.50  1.28  6.56
1    3.00  2.30  3.6  2.87  2.30  3.60  2.87  2.30  3.60  2.87  2.24  3.72
2    3.90  1.90  3.6  3.90  1.91  3.60  3.90  1.91  3.60  3.90  1.94  3.73
3    2.30  3.10  3.4  2.25  3.10  3.40  2.25  3.10  3.40  2.25  3.27  3.43
4    8.00  1.39  4.8  8.00  1.40  4.80  8.00  1.40  4.80  8.00  1.40  4.71
..    ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
313  4.80  1.63  4.2  4.75   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
314  2.20  2.95  3.5  2.30   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
315  2.63  2.60  3.4  2.65   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
316  2.63  2.60  3.4  2.60   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
317  2.10  3.00  3.9  2.15   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

      PSA  MaxH  MaxD  MaxA  AvgH  AvgD  AvgA  BFEH  BFED  BFEA  B365>2.5  \
0    9.07  1.34  6.50  9.50  1.31  5.96  8.31  1.34  6.60  9.40      1.36
1    3.13  2.38  3.75  3.10  2.30  3.56  2.94  2.40  3.75  3.10      1.62
2    3.98  1.95  3.75  4.00  1.92  3.62  3.91  1.99  3.85  4.20      1.73
3    2.29  3.25  3.50  2.30  3.17  3.38  2.26  3.35  3.50  2.34      1.93
4    8.79  1.40  5.00  9.50  1.37  4.80  8.30  1.42  5.20  9.60      1.73
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...       ...
313   NaN  1.65  4.35  5.10  1.62  4.18  4.83  1.72  4.40  5.20      1.57
314   NaN  3.20  3.60  2.30  3.07  3.50  2.22  3.25  3.70  2.32      1.73
315   NaN  2.66  3.50  2.70  2.61  3.33  2.65  2.78  3.45  2.82      2.00
316   NaN  2.70  3.50  2.70  2.62  3.34  2.63  2.78  3.50  2.78      2.00
317   NaN  3.30  4.00  2.15  3.08  3.80  2.10  3.35  4.00  2.16      1.57

     B365<2.5  P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  Avg<2.5  BFE>2.5  \
0        3.20   1.37   3.26     1.38     3.30     1.35     3.13     1.40
1        2.30   1.65   2.33     1.65     2.33     1.61     2.25     1.72
2        2.10   1.76   2.15     1.74     2.15     1.71     2.08     1.78
3        1.93   1.98   1.91     1.94     1.93     1.88     1.88     2.02
4        2.10   1.74   2.17     1.73     2.30     1.66     2.16     1.75
..        ...    ...    ...      ...      ...      ...      ...      ...
313      2.38    NaN    NaN     1.57     2.50     1.53     2.42     1.59
314      2.10    NaN    NaN     1.76     2.10     1.71     2.07     1.80
315      1.85    NaN    NaN     2.00     1.91     1.91     1.84     2.06
316      1.85    NaN    NaN     2.00     1.91     1.92     1.83     2.08
317      2.38    NaN    NaN     1.60     2.50     1.54     2.40     1.59

     BFE<2.5   AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  \
0       3.40 -1.50     1.83     2.03  1.90  2.03    1.83    2.06    1.78
1       2.36 -0.25     2.00     1.85  1.96  1.94    2.00    1.87    1.90
2       2.22 -0.50     1.93     1.93  1.95  1.95    1.93    1.93    1.87
3       1.96  0.25     1.90     1.95  1.93  1.98    1.90    1.95    1.84
4       2.28 -1.25     1.88     1.98  1.89  2.01    1.88    1.98    1.75
..       ...   ...      ...      ...   ...   ...     ...     ...     ...
313     2.62 -0.75     1.80     2.05   NaN   NaN    1.83    2.05    1.77
314     2.22  0.25     1.93     1.93   NaN   NaN    1.93    1.93    1.88
315     1.92  0.00     1.93     1.93   NaN   NaN    1.93    1.93    1.88
316     1.89  0.00     1.93     1.93   NaN   NaN    1.93    1.93    1.88
317     2.62  0.25     1.98     1.88   NaN   NaN    1.98    1.88    1.93

     AvgAHA  BFEAHH  BFEAHA  B365CH  B365CD  B365CA  BFDCH  BFDCD  BFDCA  \
0      1.99    1.90    2.08    1.29    6.25    9.00   1.30   6.00   9.50
1      1.78    2.08    1.90    2.45    3.40    2.80   2.38   3.50   3.10
2      1.88    1.99    2.00    1.80    3.70    4.33   1.83   3.75   4.33
3      1.81    1.97    2.01    3.40    3.20    2.25   3.40   3.30   2.30
4      1.95    1.93    2.03    1.55    3.90    6.25   1.57   4.00   6.50
..      ...     ...     ...     ...     ...     ...    ...    ...    ...
313    1.99    1.90    2.09    1.75    4.10    4.20   1.73   4.20   4.33
314    1.89    1.97    2.01    3.00    3.30    2.40   3.00   3.40   2.40
315    1.89    1.98    1.98    2.30    3.40    3.00   2.40   3.50   2.88
316    1.88    1.99    1.99    2.90    3.20    2.55   2.75   3.40   2.60
317    1.83    2.09    1.90    3.60    3.90    1.91   3.50   4.00   1.95

     BMGMCH  BMGMCD  BMGMCA  BVCH  BVCD  BVCA  BWCH  BWCD  BWCA  CLCH  CLCD  \
0      1.30    6.25    9.00  1.29  6.00  9.00  1.31  5.75  8.00  1.30  6.00
1      2.40    3.45    2.95  2.38  3.30  3.00  2.40  3.40  2.85  2.37  3.50
2      1.87    3.65    4.30  1.83  3.60  4.33  1.85  3.60  4.10  1.85  3.60
3      3.55    3.10    2.30  3.40  3.13  2.25  3.30  3.25  2.25  3.30  3.25
4      1.55    4.10    6.50  1.53  3.90  5.75  1.55  4.10  6.00  1.55  4.00
..      ...     ...     ...   ...   ...   ...   ...   ...   ...   ...   ...
313    1.70    3.90    4.40  1.70  4.20  4.40  1.73  4.20  4.10   NaN   NaN
314    2.90    3.25    2.40  2.90  3.25  2.45  2.80  3.40  2.45   NaN   NaN
315    2.43    3.20    2.95  2.30  3.30  3.10  2.30  3.40  3.00   NaN   NaN
316    2.75    3.25    2.55  2.75  3.50  2.45  2.75  3.30  2.55   NaN   NaN
317    3.55    3.85    1.91  3.50  4.00  1.93  3.50  3.80  1.95   NaN   NaN

     CLCA  LBCH  LBCD  LBCA  PSCH  PSCD  PSCA  MaxCH  MaxCD  MaxCA  AvgCH  \
0    8.00  1.30  5.75  8.00  1.29  6.55  9.75   1.31   6.60   9.50   1.29
1    2.87  2.37  3.50  2.87  2.32  3.63  3.07   2.45   3.50   3.10   2.38
2    4.20  1.85  3.60  4.00  1.92  3.66  4.27   1.87   3.75   4.40   1.83
3    2.25  3.25  3.20  2.25  3.55  3.24  2.29   3.55   3.30   2.31   3.40
4    6.00  1.55  4.00  6.00  1.56  4.20  6.70   1.58   4.10   6.50   1.55
..    ...   ...   ...   ...   ...   ...   ...    ...    ...    ...    ...
313   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.78   4.20   5.00   1.71
314   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.00   3.50   2.50   2.91
315   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.50   3.50   3.10   2.35
316   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.90   3.50   2.63   2.75
317   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.60   4.00   2.10   3.48

     AvgCD  AvgCA  BFECH  BFECD  BFECA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  \
0     6.02   8.68   1.32   6.80  10.00       1.36       3.20    1.41    2.95
1     3.41   2.93   2.48   3.55   3.10       1.83       2.03    1.66    2.31
2     3.64   4.26   1.90   3.80   4.60       1.88       1.98    1.91    2.00
3     3.17   2.25   3.60   3.40   2.32       2.10       1.73    2.24    1.70
4     4.01   6.16   1.61   4.30   6.80       1.93       1.93    1.91    2.00
..     ...    ...    ...    ...    ...        ...        ...     ...     ...
313   4.06   4.38   1.79   4.20   4.80       1.50       2.63     NaN     NaN
314   3.30   2.42   3.10   3.40   2.58       1.91       1.91     NaN     NaN
315   3.32   2.99   2.48   3.45   3.20       1.80       2.00     NaN     NaN
316   3.31   2.53   2.94   3.45   2.66       1.80       2.00     NaN     NaN
317   3.89   1.94   3.75   4.20   2.00       1.53       2.50     NaN     NaN

     MaxC>2.5  MaxC<2.5  AvgC>2.5  AvgC<2.5  BFEC>2.5  BFEC<2.5  AHCh  \
0        1.40      3.20      1.36      3.05      1.41      3.40 -1.75
1        1.83      2.18      1.75      2.04      1.87      2.12 -0.25
2        1.91      2.04      1.84      1.93      1.93      2.06 -0.50
3        2.25      1.75      2.11      1.69      2.20      1.80  0.25
4        1.93      1.93      1.88      1.88      1.99      2.00 -1.00
..        ...       ...       ...       ...       ...       ...   ...
313      1.52      2.65      1.50      2.54      1.55      2.78 -0.75
314      1.91      2.05      1.85      1.91      1.98      2.00  0.00
315      2.00      2.00      1.87      1.90      2.08      1.91 -0.25
316      1.89      2.00      1.81      1.95      1.90      2.08  0.00
317      1.54      2.70      1.50      2.55      1.57      2.72  0.50

     B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  \
0        2.03      1.78   2.07   1.85     2.03     1.88     1.94     1.76
1        2.05      1.80   2.02   1.89     2.06     1.80     1.95     1.74
2        1.83      2.03   1.93   2.00     1.84     2.03     1.80     1.96
3        1.95      1.90   1.97   1.95     1.95     1.94     1.86     1.78
4        1.98      1.88   1.99   1.93     1.98     1.91     1.88     1.83
..        ...       ...    ...    ...      ...      ...      ...      ...
313      1.98      1.88    NaN    NaN     1.98     1.93     1.88     1.88
314      2.10      1.78    NaN    NaN     2.10     1.78     2.05     1.73
315      2.00      1.85    NaN    NaN     2.00     1.85     1.97     1.80
316      2.05      1.80    NaN    NaN     2.05     1.85     1.99     1.78
317      1.93      1.93    NaN    NaN     1.93     1.93     1.85     1.87

     BFECAHH  BFECAHA
0       2.14     1.86
1       2.14     1.86
2       1.91     2.08
3       2.02     1.97
4       2.07     1.92
..       ...      ...
313     1.98     1.99
314     2.19     1.83
315     2.12     1.87
316     2.09     1.90
317     1.99     2.00

[318 rows x 132 columns]

In [4]:
# reading 1 csv file from a website without serving it to a variable
pd.read_csv("https://www.football-data.co.uk/mmz4281/2526/E0.csv")

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BFDH,BFDD,BFDA,BMGMH,BMGMD,BMGMA,BVH,BVD,BVA,BWH,BWD,BWA,CLH,CLD,CLA,LBH,LBD,LBA,PSH,PSD,PSA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,BFEH,BFED,BFEA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,BFE>2.5,BFE<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,BFEAHH,BFEAHA,B365CH,B365CD,B365CA,BFDCH,BFDCD,BFDCA,BMGMCH,BMGMCD,BMGMCA,BVCH,BVCD,BVCA,BWCH,BWCD,BWCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA,PSCH,PSCD,PSCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,BFEC>2.5,BFEC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,H,A Taylor,19,10,10,3,7,10,6,7,1,2,0,0,1.30,6.00,8.50,1.30,6.00,9.50,1.29,6.50,9.00,1.30,6.0,8.50,1.32,5.5,7.50,1.33,5.75,8.00,1.33,5.75,7.50,1.28,6.56,9.07,1.34,6.50,9.50,1.31,5.96,8.31,1.34,6.60,9.40,1.36,3.20,1.37,3.26,1.38,3.30,1.35,3.13,1.40,3.40,-1.50,1.83,2.03,1.90,2.03,1.83,2.06,1.78,1.99,1.90,2.08,1.29,6.25,9.00,1.30,6.00,9.50,1.30,6.25,9.00,1.29,6.00,9.00,1.31,5.75,8.00,1.30,6.00,8.00,1.30,5.75,8.00,1.29,6.55,9.75,1.31,6.60,9.50,1.29,6.02,8.68,1.32,6.80,10.00,1.36,3.20,1.41,2.95,1.40,3.20,1.36,3.05,1.41,3.40,-1.75,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,D,C Pawson,3,16,3,3,13,11,3,6,1,1,1,0,2.25,3.50,2.90,2.25,3.75,3.10,2.38,3.55,2.95,2.30,3.5,3.00,2.30,3.6,2.87,2.30,3.60,2.87,2.30,3.60,2.87,2.24,3.72,3.13,2.38,3.75,3.10,2.30,3.56,2.94,2.40,3.75,3.10,1.62,2.30,1.65,2.33,1.65,2.33,1.61,2.25,1.72,2.36,-0.25,2.00,1.85,1.96,1.94,2.00,1.87,1.90,1.78,2.08,1.90,2.45,3.40,2.80,2.38,3.50,3.10,2.40,3.45,2.95,2.38,3.30,3.00,2.40,3.40,2.85,2.37,3.50,2.87,2.37,3.50,2.87,2.32,3.63,3.07,2.45,3.50,3.10,2.38,3.41,2.93,2.48,3.55,3.10,1.83,2.03,1.66,2.31,1.83,2.18,1.75,2.04,1.87,2.12,-0.25,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,D,S Barrott,10,7,4,2,16,15,4,3,3,3,0,0,1.91,3.60,4.00,1.95,3.75,4.00,1.92,3.65,4.00,1.91,3.6,3.90,1.90,3.6,3.90,1.91,3.60,3.90,1.91,3.60,3.90,1.94,3.73,3.98,1.95,3.75,4.00,1.92,3.62,3.91,1.99,3.85,4.20,1.73,2.10,1.76,2.15,1.74,2.15,1.71,2.08,1.78,2.22,-0.50,1.93,1.93,1.95,1.95,1.93,1.93,1.87,1.88,1.99,2.00,1.80,3.70,4.33,1.83,3.75,4.33,1.87,3.65,4.30,1.83,3.60,4.33,1.85,3.60,4.10,1.85,3.60,4.20,1.85,3.60,4.00,1.92,3.66,4.27,1.87,3.75,4.40,1.83,3.64,4.26,1.90,3.80,4.60,1.88,1.98,1.91,2.00,1.91,2.04,1.84,1.93,1.93,2.06,-0.50,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,D,R Jones,10,12,5,4,8,10,5,7,0,1,0,0,3.25,3.40,2.25,3.20,3.50,2.30,3.25,3.50,2.25,3.20,3.3,2.30,3.10,3.4,2.25,3.10,3.40,2.25,3.10,3.40,2.25,3.27,3.43,2.29,3.25,3.50,2.30,3.17,3.38,2.26,3.35,3.50,2.34,1.93,1.93,1.98,1.91,1.94,1.93,1.88,1.88,2.02,1.96,0.25,1.90,1.95,1.93,1.98,1.90,1.95,1.84,1.81,1.97,2.01,3.40,3.20,2.25,3.40,3.30,2.30,3.55,3.10,2.30,3.40,3.13,2.25,3.30,3.25,2.25,3.30,3.25,2.25,3.25,3.20,2.25,3.55,3.24,2.29,3.55,3.30,2.31,3.40,3.17,2.25,3.60,3.40,2.32,2.10,1.73,2.24,1.70,2.25,1.75,2.11,1.69,2.20,1.80,0.25,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,H,M Oliver,16,14,6,4,14,8,6,5,0,0,0,0,1.38,4.75,8.50,1.36,5.00,9.50,1.37,5.00,9.00,1.33,4.6,8.00,1.39,4.8,8.00,1.40,4.80,8.00,1.40,4.80,8.00,1.40,4.71,8.79,1.40,5.00,9.50,1.37,4.80,8.30,1.42,5.20,9.60,1.73,2.10,1.74,2.17,1.73,2.30,1.66,2.16,1.75,2.28,-1.25,1.88,1.98,1.89,2.01,1.88,1.98,1.75,1.95,1.93,2.03,1.55,3.90,6.25,1.57,4.00,6.50,1.55,4.10,6.50,1.53,3.90,5.75,1.55,4.10,6.00,1.55,4.00,6.00,1.55,4.00,6.00,1.56,4.20,6.70,1.58,4.10,6.50,1.55,4.01,6.16,1.61,4.30,6.80,1.93,1.93,1.91,2.00,1.93,1.93,1.88,1.88,1.99,2.00,-1.00,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,E0,11/04/2026,17:30,Liverpool,Fulham,2,0,H,2,0,H,A Taylor,18,19,5,4,10,4,6,9,0,0,0,0,1.65,4.20,4.75,1.62,4.20,5.00,1.58,4.30,5.00,1.65,4.2,4.80,1.63,4.2,4.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.65,4.35,5.10,1.62,4.18,4.83,1.72,4.40,5.20,1.57,2.38,NaN,NaN,1.57,2.50,1.53,2.42,1.59,2.62,-0.75,1.80,2.05,NaN,NaN,1.83,2.05,1.77,1.99,1.90,2.09,1.75,4.10,4.20,1.73,4.20,4.33,1.70,3.90,4.40,1.70,4.20,4.40,1.73,4.20,4.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.78,4.20,5.00,1.71,4.06,4.38,1.79,4.20,4.80,1.50,2.63,NaN,NaN,1.52,2.65,1.50,2.54,1.55,2.78,-0.75,1.98,1.88,NaN,NaN,1.98,1.93,1.88,1.88,1.98,1.99
314,E0,12/04/2026,14:00,Crystal Palace,Newcastle,2,1,H,0,1,A,A Madley,11,7,5,3,17,12,2,4,0,3,0,0,3.00,3.60,2.20,3.10,3.60,2.25,3.15,3.35,2.23,3.10,3.6,2.20,2.95,3.5,2.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.20,3.60,2.30,3.07,3.50,2.22,3.25,3.70,2.32,1.73,2.10,NaN,NaN,1.76,2.10,1.71,2.07,1.80,2.22,0.25,1.93,1.93,NaN,NaN,1.93,1.93,1.88,1.89,1.97,2.01,3.00,3.30,2.40,3.00,3.40,2.40,2.90,3.25,2.40,2.90,3.25,2.45,2.80,3.40,2.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,3.50,2.50,2.91,3.30,2.42,3.10,3.40,2.58,1.91,1.91,NaN,NaN,1.91,2.05,1.85,1.91,1.98,2.00,0.00,2.10,1.78,NaN,NaN,2.10,1.78,2.05,1.73,2.19,1.83
315,E0,12/04/2026,14:00,Nott'm Forest,Aston Villa,1,1,D,1,1,D,M Salisbury,15,12,4,5,15,10,7,3,2,2,0,0,2.63,3.30,2.70,2.60,3.50,2.63,2.60,3.30,2.65,2.63,3.4,2.63,2.60,3.4,2.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.66,3.50,2.70,2.61,3.33,2.65,2.78,3.45,2.82,2.00,1.85,NaN,NaN,2.00,1.91,1.91,1.84,2.06,1.92,0.00,1.93,1.93,NaN,NaN,1.93,1.93,1.88,1.89,1.98,1.98,2.30,3.40,3.00,2.40,3.50,2.88,2.43,3.20,2.95,2.30,3.30,3.10,2.30,3.40,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.50,3.50,3.10,2.35,3.32,2.99,2.48,3.45,3.20,1.80,2.00,NaN,NaN,2.00,2.00,1.87,1.90,2.08,1.91,-0.25,2.00,1.85,NaN,NaN,2.00,1.85,1.97,1.80,2.12,1.87
316,E0,12/04/2026,14:00,Sunderland,Tottenham,1,0,H,0,0,D,R Jones,13,11,2,7,14,15,2,6,3,3,0,0,2.70,3.20,2.70,2.63,3.50,2.63,2.63,3.25,2.65,2.63,3.4,2.63,2.60,3.4,2.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.70,3.50,2.70,2.62,3.34,2.63,2.78,3.50,2.78,2.00,1.85,NaN,NaN,2.00,1.91,1.92,1.83,2.08,1.89,0.00,1.93,1.93,NaN,NaN,1.93,1.93,1.88,1.88,1.99,1.99,2.90,3.20,2.55,2.75,3.40,2.60,2.75,3.25,2.55,2.75,3.50,2.45,2.75,3.30,2.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.90,3.50,2.63,2.75,3.31,2.53,2.94,3.45,2.66,1.80,2.00,NaN,NaN,1.89,2.00,1.81,1.95,1.90,2.08,0.00,2.05,1.80,NaN,NaN,2.05,1.85,1.99,1.78,2.09,1.90
317,E0,12/04/2026,16:30,Chelsea,Man City,0,3,A,0,0,D,C Kavanagh,12,18,3,8,10,14,4,12,3,1,0,0,3.10,3.80,2.15,3.10,4.00,2.10,3.25,3.65,2.05,3.00,3.7,2.10,3.00,3.9,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.30,4.00,2.15,3.08,3.80,2.10,3.35,4.00,2.16,1.57,2.38,NaN,NaN,1.60,2.50,1.54,2.40,1.59,2.62,0.25,1.98,1.88,NaN,NaN,1.98,1.88,1.93,1.83,2.09,1.90,3.60,3.90,1.91,3.50,4.00,1.95,3.55,3.85,1.91,3.50,4.00,1.93,3.50,3.80,1.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.60,4.00,2.10,3.48,3.89,1.94,3.75,4.20,2.00,1.53,2.50,NaN,NaN,1.54,2.70,1.50,2.55,1.57,2.72,0.50,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.99,2.00

In [5]:
# rename columns                                                                                        
df_pr2526.rename(columns={ "FTHG": "HomeGoals", "FTAG": "AwayGoals"}, inplace=True)

In [6]:
print(df_pr2526)

    Div        Date   Time        HomeTeam     AwayTeam  HomeGoals  AwayGoals  \
0    E0  15/08/2025  20:00       Liverpool  Bournemouth          4          2
1    E0  16/08/2025  12:30     Aston Villa    Newcastle          0          0
2    E0  16/08/2025  15:00        Brighton       Fulham          1          1
3    E0  16/08/2025  15:00      Sunderland     West Ham          3          0
4    E0  16/08/2025  15:00       Tottenham      Burnley          3          0
..   ..         ...    ...             ...          ...        ...        ...
313  E0  11/04/2026  17:30       Liverpool       Fulham          2          0
314  E0  12/04/2026  14:00  Crystal Palace    Newcastle          2          1
315  E0  12/04/2026  14:00   Nott'm Forest  Aston Villa          1          1
316  E0  12/04/2026  14:00      Sunderland    Tottenham          1          0
317  E0  12/04/2026  16:30         Chelsea     Man City          0          3

    FTR  HTHG  HTAG HTR      Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  \
0     H     1     0   H     A Taylor  19  10   10    3   7  10   6   7   1
1     D     0     0   D     C Pawson   3  16    3    3  13  11   3   6   1
2     D     0     0   D    S Barrott  10   7    4    2  16  15   4   3   3
3     H     0     0   D      R Jones  10  12    5    4   8  10   5   7   0
4     H     1     0   H     M Oliver  16  14    6    4  14   8   6   5   0
..   ..   ...   ...  ..          ...  ..  ..  ...  ...  ..  ..  ..  ..  ..
313   H     2     0   H     A Taylor  18  19    5    4  10   4   6   9   0
314   H     0     1   A     A Madley  11   7    5    3  17  12   2   4   0
315   D     1     1   D  M Salisbury  15  12    4    5  15  10   7   3   2
316   H     0     0   D      R Jones  13  11    2    7  14  15   2   6   3
317   A     0     0   D   C Kavanagh  12  18    3    8  10  14   4  12   3

     AY  HR  AR  B365H  B365D  B365A  BFDH  BFDD  BFDA  BMGMH  BMGMD  BMGMA  \
0     2   0   0   1.30   6.00   8.50  1.30  6.00  9.50   1.29   6.50   9.00
1     1   1   0   2.25   3.50   2.90  2.25  3.75  3.10   2.38   3.55   2.95
2     3   0   0   1.91   3.60   4.00  1.95  3.75  4.00   1.92   3.65   4.00
3     1   0   0   3.25   3.40   2.25  3.20  3.50  2.30   3.25   3.50   2.25
4     0   0   0   1.38   4.75   8.50  1.36  5.00  9.50   1.37   5.00   9.00
..   ..  ..  ..    ...    ...    ...   ...   ...   ...    ...    ...    ...
313   0   0   0   1.65   4.20   4.75  1.62  4.20  5.00   1.58   4.30   5.00
314   3   0   0   3.00   3.60   2.20  3.10  3.60  2.25   3.15   3.35   2.23
315   2   0   0   2.63   3.30   2.70  2.60  3.50  2.63   2.60   3.30   2.65
316   3   0   0   2.70   3.20   2.70  2.63  3.50  2.63   2.63   3.25   2.65
317   1   0   0   3.10   3.80   2.15  3.10  4.00  2.10   3.25   3.65   2.05

      BVH  BVD   BVA   BWH  BWD   BWA   CLH   CLD   CLA   LBH   LBD   LBA  \
0    1.30  6.0  8.50  1.32  5.5  7.50  1.33  5.75  8.00  1.33  5.75  7.50
1    2.30  3.5  3.00  2.30  3.6  2.87  2.30  3.60  2.87  2.30  3.60  2.87
2    1.91  3.6  3.90  1.90  3.6  3.90  1.91  3.60  3.90  1.91  3.60  3.90
3    3.20  3.3  2.30  3.10  3.4  2.25  3.10  3.40  2.25  3.10  3.40  2.25
4    1.33  4.6  8.00  1.39  4.8  8.00  1.40  4.80  8.00  1.40  4.80  8.00
..    ...  ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...
313  1.65  4.2  4.80  1.63  4.2  4.75   NaN   NaN   NaN   NaN   NaN   NaN
314  3.10  3.6  2.20  2.95  3.5  2.30   NaN   NaN   NaN   NaN   NaN   NaN
315  2.63  3.4  2.63  2.60  3.4  2.65   NaN   NaN   NaN   NaN   NaN   NaN
316  2.63  3.4  2.63  2.60  3.4  2.60   NaN   NaN   NaN   NaN   NaN   NaN
317  3.00  3.7  2.10  3.00  3.9  2.15   NaN   NaN   NaN   NaN   NaN   NaN

      PSH   PSD   PSA  MaxH  MaxD  MaxA  AvgH  AvgD  AvgA  BFEH  BFED  BFEA  \
0    1.28  6.56  9.07  1.34  6.50  9.50  1.31  5.96  8.31  1.34  6.60  9.40
1    2.24  3.72  3.13  2.38  3.75  3.10  2.30  3.56  2.94  2.40  3.75  3.10
2    1.94  3.73  3.98  1.95  3.75  4.00  1.92  3.62  3.91  1.99  3.85  4.20
3    3.27  3.43  2.29  3.25  3.50  2.30  3.17  3.38  2.26  3.35  3.50  2.34
4    1.40  4.71  8.79  1.40  5.00  9.50  1.37  4.80  8.30  1.42  5.20  9.60
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
313   NaN   NaN   NaN  1.65  4.35  5.10  1.62  4.18  4.83  1.72  4.40  5.20
314   NaN   NaN   NaN  3.20  3.60  2.30  3.07  3.50  2.22  3.25  3.70  2.32
315   NaN   NaN   NaN  2.66  3.50  2.70  2.61  3.33  2.65  2.78  3.45  2.82
316   NaN   NaN   NaN  2.70  3.50  2.70  2.62  3.34  2.63  2.78  3.50  2.78
317   NaN   NaN   NaN  3.30  4.00  2.15  3.08  3.80  2.10  3.35  4.00  2.16

     B365>2.5  B365<2.5  P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  Avg<2.5  \
0        1.36      3.20   1.37   3.26     1.38     3.30     1.35     3.13
1        1.62      2.30   1.65   2.33     1.65     2.33     1.61     2.25
2        1.73      2.10   1.76   2.15     1.74     2.15     1.71     2.08
3        1.93      1.93   1.98   1.91     1.94     1.93     1.88     1.88
4        1.73      2.10   1.74   2.17     1.73     2.30     1.66     2.16
..        ...       ...    ...    ...      ...      ...      ...      ...
313      1.57      2.38    NaN    NaN     1.57     2.50     1.53     2.42
314      1.73      2.10    NaN    NaN     1.76     2.10     1.71     2.07
315      2.00      1.85    NaN    NaN     2.00     1.91     1.91     1.84
316      2.00      1.85    NaN    NaN     2.00     1.91     1.92     1.83
317      1.57      2.38    NaN    NaN     1.60     2.50     1.54     2.40

     BFE>2.5  BFE<2.5   AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  \
0       1.40     3.40 -1.50     1.83     2.03  1.90  2.03    1.83    2.06
1       1.72     2.36 -0.25     2.00     1.85  1.96  1.94    2.00    1.87
2       1.78     2.22 -0.50     1.93     1.93  1.95  1.95    1.93    1.93
3       2.02     1.96  0.25     1.90     1.95  1.93  1.98    1.90    1.95
4       1.75     2.28 -1.25     1.88     1.98  1.89  2.01    1.88    1.98
..       ...      ...   ...      ...      ...   ...   ...     ...     ...
313     1.59     2.62 -0.75     1.80     2.05   NaN   NaN    1.83    2.05
314     1.80     2.22  0.25     1.93     1.93   NaN   NaN    1.93    1.93
315     2.06     1.92  0.00     1.93     1.93   NaN   NaN    1.93    1.93
316     2.08     1.89  0.00     1.93     1.93   NaN   NaN    1.93    1.93
317     1.59     2.62  0.25     1.98     1.88   NaN   NaN    1.98    1.88

     AvgAHH  AvgAHA  BFEAHH  BFEAHA  B365CH  B365CD  B365CA  BFDCH  BFDCD  \
0      1.78    1.99    1.90    2.08    1.29    6.25    9.00   1.30   6.00
1      1.90    1.78    2.08    1.90    2.45    3.40    2.80   2.38   3.50
2      1.87    1.88    1.99    2.00    1.80    3.70    4.33   1.83   3.75
3      1.84    1.81    1.97    2.01    3.40    3.20    2.25   3.40   3.30
4      1.75    1.95    1.93    2.03    1.55    3.90    6.25   1.57   4.00
..      ...     ...     ...     ...     ...     ...     ...    ...    ...
313    1.77    1.99    1.90    2.09    1.75    4.10    4.20   1.73   4.20
314    1.88    1.89    1.97    2.01    3.00    3.30    2.40   3.00   3.40
315    1.88    1.89    1.98    1.98    2.30    3.40    3.00   2.40   3.50
316    1.88    1.88    1.99    1.99    2.90    3.20    2.55   2.75   3.40
317    1.93    1.83    2.09    1.90    3.60    3.90    1.91   3.50   4.00

     BFDCA  BMGMCH  BMGMCD  BMGMCA  BVCH  BVCD  BVCA  BWCH  BWCD  BWCA  CLCH  \
0     9.50    1.30    6.25    9.00  1.29  6.00  9.00  1.31  5.75  8.00  1.30
1     3.10    2.40    3.45    2.95  2.38  3.30  3.00  2.40  3.40  2.85  2.37
2     4.33    1.87    3.65    4.30  1.83  3.60  4.33  1.85  3.60  4.10  1.85
3     2.30    3.55    3.10    2.30  3.40  3.13  2.25  3.30  3.25  2.25  3.30
4     6.50    1.55    4.10    6.50  1.53  3.90  5.75  1.55  4.10  6.00  1.55
..     ...     ...     ...     ...   ...   ...   ...   ...   ...   ...   ...
313   4.33    1.70    3.90    4.40  1.70  4.20  4.40  1.73  4.20  4.10   NaN
314   2.40    2.90    3.25    2.40  2.90  3.25  2.45  2.80  3.40  2.45   NaN
315   2.88    2.43    3.20    2.95  2.30  3.30  3.10  2.30  3.40  3.00   NaN
316   2.60    2.75    3.25    2.55  2.75  3.50  2.45  2.75  3.30  2.55   NaN
317   1.95    3.55    3.85    1.91  3.50  4.00  1.93  3.50  3.80  1.95   NaN

     CLCD  CLCA  LBCH  LBCD  LBCA  PSCH  PSCD  PSCA  MaxCH  MaxCD  MaxCA  \
0    6.00  8.00  1.30  5.75  8.00  1.29  6.55  9.75   1.31   6.60   9.50
1    3.50  2.87  2.37  3.50  2.87  2.32  3.63  3.07   2.45   3.50   3.10
2    3.60  4.20  1.85  3.60  4.00  1.92  3.66  4.27   1.87   3.75   4.40
3    3.25  2.25  3.25  3.20  2.25  3.55  3.24  2.29   3.55   3.30   2.31
4    4.00  6.00  1.55  4.00  6.00  1.56  4.20  6.70   1.58   4.10   6.50
..    ...   ...   ...   ...   ...   ...   ...   ...    ...    ...    ...
313   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.78   4.20   5.00
314   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.00   3.50   2.50
315   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.50   3.50   3.10
316   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.90   3.50   2.63
317   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.60   4.00   2.10

     AvgCH  AvgCD  AvgCA  BFECH  BFECD  BFECA  B365C>2.5  B365C<2.5  PC>2.5  \
0     1.29   6.02   8.68   1.32   6.80  10.00       1.36       3.20    1.41
1     2.38   3.41   2.93   2.48   3.55   3.10       1.83       2.03    1.66
2     1.83   3.64   4.26   1.90   3.80   4.60       1.88       1.98    1.91
3     3.40   3.17   2.25   3.60   3.40   2.32       2.10       1.73    2.24
4     1.55   4.01   6.16   1.61   4.30   6.80       1.93       1.93    1.91
..     ...    ...    ...    ...    ...    ...        ...        ...     ...
313   1.71   4.06   4.38   1.79   4.20   4.80       1.50       2.63     NaN
314   2.91   3.30   2.42   3.10   3.40   2.58       1.91       1.91     NaN
315   2.35   3.32   2.99   2.48   3.45   3.20       1.80       2.00     NaN
316   2.75   3.31   2.53   2.94   3.45   2.66       1.80       2.00     NaN
317   3.48   3.89   1.94   3.75   4.20   2.00       1.53       2.50     NaN

     PC<2.5  MaxC>2.5  MaxC<2.5  AvgC>2.5  AvgC<2.5  BFEC>2.5  BFEC<2.5  AHCh  \
0      2.95      1.40      3.20      1.36      3.05      1.41      3.40 -1.75
1      2.31      1.83      2.18      1.75      2.04      1.87      2.12 -0.25
2      2.00      1.91      2.04      1.84      1.93      1.93      2.06 -0.50
3      1.70      2.25      1.75      2.11      1.69      2.20      1.80  0.25
4      2.00      1.93      1.93      1.88      1.88      1.99      2.00 -1.00
..      ...       ...       ...       ...       ...       ...       ...   ...
313     NaN      1.52      2.65      1.50      2.54      1.55      2.78 -0.75
314     NaN      1.91      2.05      1.85      1.91      1.98      2.00  0.00
315     NaN      2.00      2.00      1.87      1.90      2.08      1.91 -0.25
316     NaN      1.89      2.00      1.81      1.95      1.90      2.08  0.00
317     NaN      1.54      2.70      1.50      2.55      1.57      2.72  0.50

     B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  \
0        2.03      1.78   2.07   1.85     2.03     1.88     1.94     1.76
1        2.05      1.80   2.02   1.89     2.06     1.80     1.95     1.74
2        1.83      2.03   1.93   2.00     1.84     2.03     1.80     1.96
3        1.95      1.90   1.97   1.95     1.95     1.94     1.86     1.78
4        1.98      1.88   1.99   1.93     1.98     1.91     1.88     1.83
..        ...       ...    ...    ...      ...      ...      ...      ...
313      1.98      1.88    NaN    NaN     1.98     1.93     1.88     1.88
314      2.10      1.78    NaN    NaN     2.10     1.78     2.05     1.73
315      2.00      1.85    NaN    NaN     2.00     1.85     1.97     1.80
316      2.05      1.80    NaN    NaN     2.05     1.85     1.99     1.78
317      1.93      1.93    NaN    NaN     1.93     1.93     1.85     1.87

     BFECAHH  BFECAHA
0       2.14     1.86
1       2.14     1.86
2       1.91     2.08
3       2.02     1.97
4       2.07     1.92
..       ...      ...
313     1.98     1.99
314     2.19     1.83
315     2.12     1.87
316     2.09     1.90
317     1.99     2.00

[318 rows x 132 columns]

### read .csv from multiple urls with Pandas

link: root + season + league

In [7]:
# link structure:       
"https://www.football-data.co.uk/mmz4281/" + "2526" + "/E0" +  ".csv"

'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

In [8]:
# create a root  variable for the link structure
root = "https://www.football-data.co.uk/mmz4281/"

### multiple leagues
+ https://www.football-data.co.uk/mmz4281/2526/E0.csv
+ https://www.football-data.co.uk/mmz4281/2526/E1.csv
+ https://www.football-data.co.uk/mmz4281/2526/E2.csv
+ https://www.football-data.co.uk/mmz4281/2526/E3.csv
+ https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [9]:
# creating a list of leagues
leagues = ["E0", "E1", "E2", "E3", "EC"]

# looping through the list of leagues and reading the csv files from the website
for league in leagues:
    url = root + "2526/" + league + ".csv"
    df = pd.read_csv(url)
    print(df.head())

  Div        Date   Time     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  15/08/2025  20:00    Liverpool  Bournemouth     4     2   H     1
1  E0  16/08/2025  12:30  Aston Villa    Newcastle     0     0   D     0
2  E0  16/08/2025  15:00     Brighton       Fulham     1     1   D     0
3  E0  16/08/2025  15:00   Sunderland     West Ham     3     0   H     0
4  E0  16/08/2025  15:00    Tottenham      Burnley     3     0   H     1

   HTAG HTR    Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  \
0     0   H   A Taylor  19  10   10    3   7  10   6   7   1   2   0   0
1     0   D   C Pawson   3  16    3    3  13  11   3   6   1   1   1   0
2     0   D  S Barrott  10   7    4    2  16  15   4   3   3   3   0   0
3     0   D    R Jones  10  12    5    4   8  10   5   7   0   1   0   0
4     0   H   M Oliver  16  14    6    4  14   8   6   5   0   0   0   0

   B365H  B365D  B365A  BFDH  BFDD  BFDA  BMGMH  BMGMD  BMGMA   BVH  BVD  BVA  \
0   1.30   6.00   8.50  1.30  6.00   9.5   1.29   6.50   9.00  1.30  6.0  8.5
1   2.25   3.50   2.90  2.25  3.75   3.1   2.38   3.55   2.95  2.30  3.5  3.0
2   1.91   3.60   4.00  1.95  3.75   4.0   1.92   3.65   4.00  1.91  3.6  3.9
3   3.25   3.40   2.25  3.20  3.50   2.3   3.25   3.50   2.25  3.20  3.3  2.3
4   1.38   4.75   8.50  1.36  5.00   9.5   1.37   5.00   9.00  1.33  4.6  8.0

    BWH  BWD   BWA   CLH   CLD   CLA   LBH   LBD   LBA   PSH   PSD   PSA  \
0  1.32  5.5  7.50  1.33  5.75  8.00  1.33  5.75  7.50  1.28  6.56  9.07
1  2.30  3.6  2.87  2.30  3.60  2.87  2.30  3.60  2.87  2.24  3.72  3.13
2  1.90  3.6  3.90  1.91  3.60  3.90  1.91  3.60  3.90  1.94  3.73  3.98
3  3.10  3.4  2.25  3.10  3.40  2.25  3.10  3.40  2.25  3.27  3.43  2.29
4  1.39  4.8  8.00  1.40  4.80  8.00  1.40  4.80  8.00  1.40  4.71  8.79

   MaxH  MaxD  MaxA  AvgH  AvgD  AvgA  BFEH  BFED  BFEA  B365>2.5  B365<2.5  \
0  1.34  6.50   9.5  1.31  5.96  8.31  1.34  6.60  9.40      1.36      3.20
1  2.38  3.75   3.1  2.30  3.56  2.94  2.40  3.75  3.10      1.62      2.30
2  1.95  3.75   4.0  1.92  3.62  3.91  1.99  3.85  4.20      1.73      2.10
3  3.25  3.50   2.3  3.17  3.38  2.26  3.35  3.50  2.34      1.93      1.93
4  1.40  5.00   9.5  1.37  4.80  8.30  1.42  5.20  9.60      1.73      2.10

   P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  Avg<2.5  BFE>2.5  BFE<2.5   AHh  \
0   1.37   3.26     1.38     3.30     1.35     3.13     1.40     3.40 -1.50
1   1.65   2.33     1.65     2.33     1.61     2.25     1.72     2.36 -0.25
2   1.76   2.15     1.74     2.15     1.71     2.08     1.78     2.22 -0.50
3   1.98   1.91     1.94     1.93     1.88     1.88     2.02     1.96  0.25
4   1.74   2.17     1.73     2.30     1.66     2.16     1.75     2.28 -1.25

   B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  AvgAHA  BFEAHH  \
0     1.83     2.03  1.90  2.03    1.83    2.06    1.78    1.99    1.90
1     2.00     1.85  1.96  1.94    2.00    1.87    1.90    1.78    2.08
2     1.93     1.93  1.95  1.95    1.93    1.93    1.87    1.88    1.99
3     1.90     1.95  1.93  1.98    1.90    1.95    1.84    1.81    1.97
4     1.88     1.98  1.89  2.01    1.88    1.98    1.75    1.95    1.93

   BFEAHA  B365CH  B365CD  B365CA  BFDCH  BFDCD  BFDCA  BMGMCH  BMGMCD  \
0    2.08    1.29    6.25    9.00   1.30   6.00   9.50    1.30    6.25
1    1.90    2.45    3.40    2.80   2.38   3.50   3.10    2.40    3.45
2    2.00    1.80    3.70    4.33   1.83   3.75   4.33    1.87    3.65
3    2.01    3.40    3.20    2.25   3.40   3.30   2.30    3.55    3.10
4    2.03    1.55    3.90    6.25   1.57   4.00   6.50    1.55    4.10

   BMGMCA  BVCH  BVCD  BVCA  BWCH  BWCD  BWCA  CLCH  CLCD  CLCA  LBCH  LBCD  \
0    9.00  1.29  6.00  9.00  1.31  5.75  8.00  1.30  6.00  8.00  1.30  5.75
1    2.95  2.38  3.30  3.00  2.40  3.40  2.85  2.37  3.50  2.87  2.37  3.50
2    4.30  1.83  3.60  4.33  1.85  3.60  4.10  1.85  3.60  4.20  1.85  3.60
3    2.30  3.40  3.13  2.25  3.30  3.25  2.25  3.30  3.25  2.25  3.25  3.20
4    6.50  1.53  3.90  5.75  1.55  4.10  6.00  1.55  4.00  6.00  1.55  4.00

   LBCA  PSCH  PSCD  PSCA  MaxCH  MaxCD  MaxCA  AvgCH  AvgCD  AvgCA  BFECH  \
0  8.00  1.29  6.55  9.75   1.31   6.60   9.50   1.29   6.02   8.68   1.32
1  2.87  2.32  3.63  3.07   2.45   3.50   3.10   2.38   3.41   2.93   2.48
2  4.00  1.92  3.66  4.27   1.87   3.75   4.40   1.83   3.64   4.26   1.90
3  2.25  3.55  3.24  2.29   3.55   3.30   2.31   3.40   3.17   2.25   3.60
4  6.00  1.56  4.20  6.70   1.58   4.10   6.50   1.55   4.01   6.16   1.61

   BFECD  BFECA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  MaxC>2.5  MaxC<2.5  \
0   6.80  10.00       1.36       3.20    1.41    2.95      1.40      3.20
1   3.55   3.10       1.83       2.03    1.66    2.31      1.83      2.18
2   3.80   4.60       1.88       1.98    1.91    2.00      1.91      2.04
3   3.40   2.32       2.10       1.73    2.24    1.70      2.25      1.75
4   4.30   6.80       1.93       1.93    1.91    2.00      1.93      1.93

   AvgC>2.5  AvgC<2.5  BFEC>2.5  BFEC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  \
0      1.36      3.05      1.41      3.40 -1.75      2.03      1.78   2.07
1      1.75      2.04      1.87      2.12 -0.25      2.05      1.80   2.02
2      1.84      1.93      1.93      2.06 -0.50      1.83      2.03   1.93
3      2.11      1.69      2.20      1.80  0.25      1.95      1.90   1.97
4      1.88      1.88      1.99      2.00 -1.00      1.98      1.88   1.99

   PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  BFECAHH  BFECAHA
0   1.85     2.03     1.88     1.94     1.76     2.14     1.86
1   1.89     2.06     1.80     1.95     1.74     2.14     1.86
2   2.00     1.84     2.03     1.80     1.96     1.91     2.08
3   1.95     1.95     1.94     1.86     1.78     2.02     1.97
4   1.93     1.98     1.91     1.88     1.83     2.07     1.92
  Div        Date   Time       HomeTeam AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  \
0  E1  08/08/2025  20:00     Birmingham  Ipswich     1     1   D     0     0
1  E1  09/08/2025  12:30       Charlton  Watford     1     0   H     0     0
2  E1  09/08/2025  12:30       Coventry     Hull     0     0   D     0     0
3  E1  09/08/2025  12:30    Southampton  Wrexham     2     1   H     0     1
4  E1  09/08/2025  15:00  Middlesbrough  Swansea     1     0   H     0     0

  HTR    Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  B365H  \
0   D  A Kitchen  11   7    3    1  16  22   1   4   2   3   0   0   2.40
1   D   S Martin  12  10    5    1   6  16   3   2   1   2   0   0   2.45
2   D   R Madley  18   7    3    3   7  11   8   2   3   3   0   0   1.73
3   A     J Bell  27  10   10    2  12  13   7   4   2   2   0   0   1.70
4   D   F Hallam   6   3    3    1  15  15   7   2   2   5   0   0   2.00

   B365D  B365A  BFDH  BFDD  BFDA  BMGMH  BMGMD  BMGMA   BVH   BVD   BVA  \
0   3.30   2.90  2.50  3.30  3.00   2.50   3.40   2.85  2.45  3.30  2.90
1   3.30   2.88  2.50  3.25  3.00   2.50   3.30   2.95  2.50  3.25  2.88
2   3.80   4.50  1.73  3.75  5.00   1.74   3.95   4.70  1.73  3.75  4.60
3   3.75   4.75  1.73  3.75  5.00   1.73   3.85   4.90  1.70  3.75  4.80
4   3.50   3.60  2.05  3.50  3.75   1.96   3.70   3.80  2.00  3.30  3.50

    BWH   BWD   BWA   CLH   CLD   CLA   LBH   LBD   LBA   PSH   PSD   PSA  \
0  2.45  3.30  2.87  2.45  3.30  2.87  2.45  3.30  2.87  2.55  3.29  2.84
1  2.50  3.25  2.85  2.50  3.25  2.87  2.50  3.25  2.80  2.54  3.15  2.95
2  1.77  3.60  4.60  1.75  3.60  4.60  1.75  3.60  4.60  1.75  3.80  4.54
3  1.72  3.75  4.80  1.73  3.75  4.80  1.70  3.75  4.80  1.72  3.77  4.83
4  1.98  3.50  3.75  2.00  3.50  3.75  2.00  3.40  3.70  2.05  3.46  3.65

   MaxH  MaxD  MaxA  AvgH  AvgD  AvgA  BFEH  BFED  BFEA  B365>2.5  B365<2.5  \
0  2.50  3.40   3.0  2.45  3.30  2.87  2.52  3.40   3.2      2.10      1.73
1  2.50  3.40   3.0  2.47  3.24  2.88  2.62  3.40   3.0      2.20      1.67
2  1.77  4.00   5.0  1.73  3.75  4.58  1.82  3.85   4.9      1.90      1.95
3  1.73  3.85   5.0  1.71  3.74  4.77  1.78  3.90   5.1      1.98      1.88
4  2.05  3.70   3.8  1.99  3.47  3.64  2.10  3.60   3.8      1.98      1.88

   P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  Avg<2.5  BFE>2.5  BFE<2.5   AHh  \
0   2.07   1.78     2.10     1.74     2.05     1.72     2.16     1.82  0.00
1   2.17   1.70     2.20     1.73     2.12     1.67     2.24     1.75  0.00
2   1.87   1.96     1.91     1.95     1.86     1.88     1.95     1.97 -0.75
3   1.99   1.85     1.98     1.91     1.89     1.84     1.99     1.92 -0.75
4   1.97   1.86     1.98     1.91     1.92     1.83     2.02     1.94 -0.50

   B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  AvgAHA  BFEAHH  \
0     1.73     2.08  1.83  2.05    1.80    2.10    1.73    2.01    1.77
1     1.80     2.05  1.79  2.08    1.80    2.05    1.76    1.98    1.84
2     1.98     1.88  1.99  1.87    1.98    1.88    1.90    1.79    2.08
3     1.95     1.90  1.94  1.91    1.95    1.90    1.88    1.81    2.00
4     2.03     1.83  2.06  1.81    2.03    1.87    1.95    1.80    2.10

   BFEAHA  B365CH  B365CD  B365CA  BFDCH  BFDCD  BFDCA  BMGMCH  BMGMCD  \
0    2.25    2.55    3.25    2.75   2.50   3.25   2.88    2.55    3.30
1    2.14    2.25    3.40    3.20   2.38   3.25   3.30    2.30    3.35
2    1.90    1.67    3.90    4.75   1.73   3.75   5.00    1.78    3.75
3    1.94    1.90    3.40    4.10   1.91   3.60   4.33    1.92    3.50
4    1.87    2.10    3.30    3.60   2.15   3.30   3.75    2.05    3.35

   BMGMCA  BVCH  BVCD  BVCA  BWCH  BWCD  BWCA  CLCH  CLCD  CLCA  LBCH  LBCD  \
0    2.88  2.50  3.25  2.88  2.55  3.20   2.8  2.60  3.20   2.8  2.50  3.20
1    3.25  2.25  3.25  3.20  2.30  3.25   3.1  2.30  3.25   3.1  2.30  3.25
2    4.75  1.67  3.75  5.00  1.68  3.70   5.0  1.85  3.60   4.8  1.73  3.70
3    4.20  1.85  3.40  4.40  1.85  3.50   4.4  1.85  3.50   4.4  1.83  3.40
4    3.95  2.05  3.30  3.70  2.10  3.30   3.5  2.05  3.40   3.6  2.05  3.40

   LBCA  PSCH  PSCD  PSCA  MaxCH  MaxCD  MaxCA  AvgCH  AvgCD  AvgCA  BFECH  \
0  2.80  2.54  3.32  2.97   2.60    3.4   2.88   2.54   3.24   2.79   2.68
1  3.10  2.26  3.35  3.40   2.38    3.4   3.33   2.27   3.26   3.20   2.38
2  4.60  1.73  3.93  4.89   1.85    3.9   5.33   1.71   3.73   4.85   1.75
3  4.33  1.75  3.83  4.89   1.92    3.6   4.50   1.88   3.43   4.24   1.94
4  3.60  1.99  3.46  4.13   2.15    3.4   4.00   2.05   3.31   3.71   2.16

   BFECD  BFECA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  MaxC>2.5  MaxC<2.5  \
0   3.45   2.94       2.10       1.73    2.22    1.71      2.18      1.73
1   3.40   3.45       2.20       1.67    2.21    1.72      2.20      1.70
2   4.10   5.30       1.93       1.93    1.90    1.99      1.93      1.93
3   3.55   4.80       2.20       1.67    1.99    1.90      2.20      1.77
4   3.45   4.00       2.05       1.68    2.08    1.83      2.15      1.76

   AvgC>2.5  AvgC<2.5  BFEC>2.5  BFEC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  \
0      2.12      1.68      2.20      1.81  0.00      1.88      1.98   1.81
1      2.15      1.66      2.30      1.75 -0.25      1.95      1.90   1.95
2      1.88      1.87      1.96      2.02 -0.75      1.88      1.98   1.95
3      2.09      1.70      2.20      1.80 -0.50      1.90      1.95   1.75
4      2.07      1.71      2.24      1.79 -0.50      2.05      1.75   2.00

   PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  BFECAHH  BFECAHA
0   2.12     1.88     1.98     1.81     1.94     1.90     2.10
1   1.95     1.95     1.90     1.86     1.83     2.03     1.95
2   1.95     1.91     1.98     1.87     1.82     1.97     2.01
3   2.18     1.90     1.95     1.84     1.91     1.92     2.07
4   1.91     2.05     1.82     2.00     1.76     2.16     1.85
  Div        Date   Time   HomeTeam       AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E2  01/08/2025  20:00      Luton  AFC Wimbledon     1     0   H     0
1  E2  02/08/2025  12:30    Cardiff      Peterboro     2     1   H     0
2  E2  02/08/2025  15:00  Blackpool      Stevenage     2     3   A     1
3  E2  02/08/2025  15:00   Bradford        Wycombe     2     1   H     2
4  E2  02/08/2025  15:00     Burton      Mansfield     2     1   H     1

   HTAG HTR        Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  \
0     0   D      T Parsons   6   2    1    0  10  11   5   2   1   1   0   0
1     1   A      B Speedie  17   7    6    3  18  10   4   2   3   1   0   0
2     2   A      M Corlett   8   7    2    4  15  19   2   2   1   4   0   0
3     0   H  S Stockbridge  12  11    6    3  23  13   2   6   3   4   0   0
4     0   H    E Duckworth  12  12    4    3  13  15   1   7   2   2   0   0

   B365H  B365D  B365A  BFDH  BFDD  BFDA  BMGMH  BMGMD  BMGMA   BVH   BVD  \
0   1.50   4.33   5.50  1.50  4.33  6.50   1.48   4.70   5.60  1.50  4.33
1   1.55   4.20   5.25  1.57  4.20  5.50   1.60   4.40   4.70  1.55  4.20
2   1.90   3.50   3.75  1.95  3.40  4.00   1.89   3.70   3.70  1.95  3.40
3   2.45   3.25   2.80  2.50  3.20  2.88   2.48   3.40   2.65  2.50  3.20
4   2.45   3.40   2.70  2.50  3.40  2.80   2.55   3.55   2.55  2.50  3.40

   BVA   BWH   BWD   BWA   CLH   CLD   CLA   LBH   LBD   LBA   PSH   PSD  \
0  6.0  1.53  4.33  5.25  1.55  4.33  5.50  1.55  4.33  5.50  1.49  4.49
1  5.5  1.58  4.20  5.00  1.60  4.33  5.00  1.60  4.33  5.00  1.57  4.32
2  3.9  1.95  3.50  3.70  1.95  3.50  3.75  1.95  3.50  3.70  1.87  3.63
3  2.8  2.40  3.25  2.80  2.45  3.30  2.87  2.45  3.30  2.87  2.50  3.33
4  2.7  2.40  3.40  2.70  2.45  3.50  2.75  2.45  3.40  2.75  2.54  3.43

    PSA  MaxH  MaxD  MaxA  AvgH  AvgD  AvgA  BFEH  BFED  BFEA  B365>2.5  \
0  6.65  1.55  4.70  6.65  1.51  4.38  5.74  1.56  4.70  6.80      1.90
1  5.50  1.60  4.40  5.50  1.57  4.26  5.10  1.62  4.30  5.70      1.58
2  4.02  1.97  3.70  4.02  1.92  3.51  3.81  1.94  3.60  4.20      2.08
3  2.82  2.50  3.40  2.88  2.46  3.28  2.79  2.60  3.30  2.96      2.15
4  2.71  2.55  3.55  2.80  2.47  3.44  2.68  2.62  3.55  2.82      1.88

   B365<2.5  P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  Avg<2.5  BFE>2.5  \
0      1.95   1.88   1.99     1.90     2.04     1.80     1.95     1.93
1      2.25   1.61   2.30     1.62     2.30     1.59     2.24     1.65
2      1.73   2.09   1.76     2.10     1.78     2.02     1.74     2.22
3      1.67   2.15   1.72     2.20     1.72     2.12     1.67     2.16
4      1.98   1.87   1.97     1.91     1.98     1.83     1.91     1.87

   BFE<2.5  AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  AvgAHA  \
0     2.04 -1.0     1.90     1.95  1.98  1.91    1.98    1.98    1.85    1.92
1     2.32 -1.0     1.98     1.88  1.95  1.92    1.98    1.92    1.91    1.83
2     1.78 -0.5     1.95     1.90  1.88  1.96    1.95    1.96    1.89    1.86
3     1.73  0.0     1.80     2.05  1.81  2.05    1.81    2.05    1.76    2.00
4     1.98  0.0     1.83     2.03  1.86  1.99    1.86    2.03    1.77    1.97

   BFEAHH  BFEAHA  B365CH  B365CD  B365CA  BFDCH  BFDCD  BFDCA  BMGMCH  \
0    1.93    1.99    1.50    3.90    6.25   1.50    4.0    7.0    1.56
1    1.99    1.90    1.67    4.10    4.50   1.67    4.0    5.0    1.68
2    1.94    1.98    2.20    3.20    3.30   2.25    3.1    3.5    2.17
3    1.84    2.08    2.38    3.20    2.90   2.40    3.2    3.0    2.50
4    1.88    2.05    3.30    3.25    2.15   3.50    3.2    2.2    3.30

   BMGMCD  BMGMCA  BVCH  BVCD  BVCA  BWCH  BWCD  BWCA  CLCH  CLCD  CLCA  LBCH  \
0    4.20    5.30  1.50   3.9  7.00  1.51  4.00  6.25  1.53  4.00  6.50  1.53
1    4.20    4.20  1.65   4.1  4.60  1.68  4.10  4.33  1.70  4.20  4.33  1.70
2    3.15    3.40  2.30   3.1  3.25  2.25  3.00  3.30  2.30  3.10  3.40  2.25
3    3.35    2.70  2.50   3.2  2.80  2.45  3.20  2.85  2.45  3.25  2.87  2.45
4    3.50    2.08  3.13   3.3  2.25  3.20  3.25  2.20  3.25  3.30  2.25  3.25

   LBCD  LBCA  PSCH  PSCD  PSCA  MaxCH  MaxCD  MaxCA  AvgCH  AvgCD  AvgCA  \
0  4.00  6.50  1.52  4.09  6.96   1.56   4.20   7.00   1.52   4.00   6.20
1  4.20  4.33  1.68  4.08  4.95   1.70   4.20   5.00   1.67   4.07   4.50
2  3.10  3.40  2.26  3.27  3.43   2.30   3.20   3.50   2.23   3.10   3.36
3  3.25  2.87  2.63  3.39  2.75   2.50   3.35   3.05   2.44   3.25   2.85
4  3.25  2.20  2.66  3.59  2.60   3.50   3.50   2.25   3.31   3.30   2.15

   BFECH  BFECD  BFECA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  MaxC>2.5  \
0   1.54   4.20   8.20       2.10       1.70    2.13    1.76      2.10
1   1.74   4.30   5.10       1.57       2.30    1.65    2.31      1.62
2   2.30   3.20   3.85       2.40       1.53    2.20    1.71      2.50
3   2.54   3.45   3.10       2.25       1.62    2.17    1.74      2.25
4   3.60   3.40   2.26       2.25       1.62    1.79    2.08      2.25

   MaxC<2.5  AvgC>2.5  AvgC<2.5  BFEC>2.5  BFEC<2.5  AHCh  B365CAHH  B365CAHA  \
0      1.79      2.02      1.73      2.22      1.79 -1.00      1.93      1.93
1      2.30      1.59      2.24      1.68      2.42 -0.75      1.85      2.00
2      1.54      2.39      1.53      2.58      1.61 -0.25      1.93      1.93
3      1.67      2.15      1.65      2.32      1.75  0.00      1.73      2.08
4      1.71      2.12      1.67      2.28      1.75  0.25      2.00      1.85

   PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  BFECAHH  BFECAHA
0   1.93   1.95     1.98     1.93     1.91     1.82     1.94     2.01
1   1.87   2.03     1.90     2.00     1.85     1.88     1.93     2.04
2   1.94   1.94     1.94     1.93     1.84     1.87     1.94     2.04
3   1.90   1.99     1.77     2.20     1.72     2.02     1.80     2.22
4   1.69   2.26     2.00     1.85     1.93     1.79     2.04     1.93
  Div        Date   Time      HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E3  02/08/2025  15:00    Accrington      Gillingham     1     1   D     0
1  E3  02/08/2025  15:00        Barnet  Fleetwood Town     0     2   A     0
2  E3  02/08/2025  15:00   Bristol Rvs       Harrogate     0     1   A     0
3  E3  02/08/2025  15:00     Cambridge      Cheltenham     1     0   H     0
4  E3  02/08/2025  15:00  Chesterfield          Barrow     1     0   H     1

   HTAG HTR      Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  \
0     0   D      O Yates  10   8    3    0  12  15   3   3   2   2   0   0
1     1   A  A Bannister  19  12    6    7  11  15   8   2   0   0   0   0
2     0   D      C Brook  17   7    2    3  10  11  13   4   1   3   0   0
3     0   D      C Hicks  13   7    4    2  11  22   4   2   0   2   0   0
4     0   H      A Young   7  10    3    1   9   9   4   3   1   1   0   0

   B365H  B365D  B365A  BFDH  BFDD  BFDA  BMGMH  BMGMD  BMGMA   BVH  BVD  \
0   2.75    3.0   2.63  2.88  3.10  2.63   2.70   3.20   2.35  2.75  3.2
1   1.95    3.5   3.60  2.00  3.40  3.75   1.92   3.35   3.45  1.95  3.5
2   1.80    3.5   4.20  1.83  3.50  4.50   1.79   3.40   3.90  1.83  3.5
3   1.83    3.6   4.00  1.90  3.60  4.00   1.78   3.45   3.85  1.85  3.7
4   1.62    3.8   5.25  1.67  3.75  5.50   1.63   3.60   4.60  1.65  3.8

    BVA   BWH  BWD   BWA   CLH   CLD  CLA   LBH   LBD  LBA   PSH   PSD   PSA  \
0  2.55  2.75  3.2  2.50  2.80  3.25  2.5  2.80  3.25  2.5  2.73  3.04  2.73
1  3.75  2.00  3.3  3.60  2.05  3.40  3.7  2.00  3.40  3.7  1.94  3.55  3.74
2  4.33  1.83  3.5  4.10  1.85  3.50  4.2  1.85  3.50  4.2  1.79  3.51  4.48
3  3.90  1.87  3.6  3.75  1.91  3.70  3.8  1.91  3.70  3.8  1.79  3.68  4.21
4  5.00  1.65  3.9  4.80  1.67  4.00  5.0  1.67  3.90  4.8  1.64  3.85  5.09

   MaxH  MaxD  MaxA  AvgH  AvgD  AvgA  BFEH  BFED  BFEA  B365>2.5  B365<2.5  \
0  2.88  3.25  2.73  2.74  3.13  2.51  2.78  3.25   2.7      2.20      1.65
1  2.05  3.55  3.75  1.96  3.39  3.58  1.97  3.60   4.0      1.98      1.88
2  1.85  3.55  4.50  1.81  3.45  4.14  1.86  3.55   4.9      2.05      1.75
3  1.91  3.70  4.21  1.83  3.56  3.89  1.90  3.70   4.1      1.75      2.05
4  1.67  4.00  5.50  1.64  3.74  4.91  1.68  3.95   6.0      1.90      1.95

   P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  Avg<2.5  BFE>2.5  BFE<2.5   AHh  \
0   2.26   1.63     2.26     1.72     2.14     1.64     2.26     1.74  0.00
1   1.90   1.90     1.98     1.91     1.90     1.83     2.06     1.90 -0.50
2   2.08   1.72     2.10     1.75     2.03     1.72     2.24     1.76 -0.50

In [10]:
# creating a list of leagues
leagues = ["E0", "E1", "E2", "E3", "EC"]

# frame_list will hold one DataFrame per league, appended in the same order
# as `leagues`. That means:
#   frame_list[0] -> data for leagues[0] ("E0")
#   frame_list[1] -> data for leagues[1] ("E1")
# and so on.

frame_list = []   # create an empty list to store the dataframes

for league in leagues:
    url = root + "2526/" + league + ".csv"
    df = pd.read_csv(url)
    # label the frame for clarity (prevents guessing by index later)
    df = df.assign(League=league)
    frame_list.append(df)

# Examples for callers:
#   - Get the E0 dataframe: frame_list[0]
#   - Get the E1 dataframe: frame_list[1]
#   - Recommended direct access by mapping:
#       frames_by_league = {df['League'].iat[0]: df for df in frame_list}
#       frames_by_league['E2']
# Avoid using print(frame_list) for large lists — inspect individual frames instead.

C:\Users\steph\AppData\Local\Temp\ipykernel_33908\223596685.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(League=league)

In [11]:
# length of frame_list
len(frame_list)

5

In [12]:
#show the 1st, 2nd, or 4th ,   5th dataframe in the list
frame_list[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HY,AY,HR,AR,B365H,B365D,B365A,BFDH,BFDD,BFDA,BMGMH,BMGMD,BMGMA,BVH,BVD,BVA,BWH,BWD,BWA,CLH,CLD,CLA,LBH,LBD,LBA,PSH,PSD,PSA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,BFEH,BFED,BFEA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,BFE>2.5,BFE<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,BFEAHH,BFEAHA,B365CH,B365CD,B365CA,BFDCH,BFDCD,BFDCA,BMGMCH,BMGMCD,BMGMCA,BVCH,BVCD,BVCA,BWCH,BWCD,BWCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA,PSCH,PSCD,PSCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,BFEC>2.5,BFEC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,League
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,H,N Smith,5,3,0,0,1.90,3.80,3.60,1.91,3.60,3.60,1.87,3.65,3.25,1.87,3.60,3.50,1.87,3.50,3.25,1.91,3.50,3.30,1.91,3.50,3.30,1.88,3.80,3.65,1.95,3.80,3.60,1.88,3.63,3.38,1.85,3.90,3.65,1.62,2.25,1.61,2.26,1.62,2.26,1.58,2.21,1.61,2.30,-0.50,1.90,1.90,1.89,1.91,1.93,1.90,1.87,1.84,NaN,NaN,1.90,3.80,3.60,1.91,3.60,3.60,1.87,3.70,3.25,1.85,3.70,3.50,1.87,3.50,3.25,1.91,3.50,3.30,1.91,3.50,3.30,1.91,3.90,3.67,1.91,3.80,3.60,1.88,3.64,3.41,2.00,4.00,3.85,1.62,2.25,1.63,2.28,1.62,2.26,1.58,2.21,1.65,2.36,-0.50,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99,EC
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,D,W Cartmel,0,3,0,0,2.88,3.40,2.38,3.00,3.10,2.38,2.75,3.25,2.28,2.90,3.20,2.30,2.87,3.10,2.20,2.87,3.10,2.25,2.87,3.10,2.25,3.07,3.19,2.35,3.10,3.40,2.38,2.87,3.19,2.29,2.92,3.00,2.32,2.05,1.75,2.06,1.74,2.05,1.75,1.99,1.72,1.97,1.64,0.25,1.80,2.00,1.80,2.01,1.80,2.00,1.76,1.95,NaN,NaN,2.70,3.40,2.50,2.80,3.10,2.50,2.75,3.30,2.25,2.70,3.13,2.45,2.65,3.10,2.35,2.80,3.10,2.25,2.80,3.10,2.25,2.87,3.22,2.56,2.85,3.40,2.50,2.75,3.17,2.37,2.96,3.40,2.66,2.05,1.75,2.09,1.76,2.05,1.75,1.98,1.73,2.14,1.82,0.00,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89,EC
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,H,D Brown,1,2,0,0,2.05,3.50,3.40,2.05,3.30,3.50,2.04,3.40,3.00,2.00,3.30,3.40,2.00,3.25,3.20,2.00,3.25,3.20,2.00,3.25,3.20,2.03,3.41,3.54,2.05,3.50,3.50,2.02,3.35,3.24,2.12,3.30,3.60,1.98,1.83,1.96,1.83,1.98,1.83,1.90,1.79,1.84,1.71,-0.50,2.05,1.75,2.04,1.78,2.05,1.75,1.99,1.72,NaN,NaN,2.00,3.50,3.40,2.05,3.30,3.50,2.04,3.45,3.05,2.00,3.40,3.30,2.05,3.25,3.10,2.05,3.25,3.10,2.00,3.25,3.20,2.15,3.46,3.38,2.06,3.50,3.50,2.01,3.37,3.26,2.06,3.55,3.85,1.95,1.85,2.00,1.84,1.95,1.85,1.89,1.80,2.02,1.93,-0.50,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84,EC
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,H,I Searle,4,3,0,0,2.25,3.20,3.20,2.25,3.10,3.20,2.10,3.15,3.10,2.20,3.13,3.10,2.10,3.10,3.10,2.10,3.10,3.10,2.10,3.10,3.10,2.29,3.23,3.14,2.25,3.25,3.25,2.16,3.14,3.11,2.28,3.15,3.15,2.10,1.70,2.09,1.71,2.10,1.70,2.04,1.68,2.08,1.73,-0.25,1.95,1.85,1.97,1.84,1.95,1.85,1.89,1.82,NaN,NaN,2.25,3.20,3.30,2.20,3.10,3.25,2.10,3.25,3.05,2.20,3.13,3.13,2.15,3.10,3.00,2.15,3.10,3.00,2.15,3.10,3.00,2.29,3.30,3.22,2.25,3.25,3.30,2.17,3.14,3.11,2.30,3.30,3.60,2.15,1.67,2.12,1.74,2.15,1.73,2.06,1.67,2.26,1.70,-0.25,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98,EC
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,A,S Morland,1,1,0,0,3.10,3.50,2.20,3.10,3.40,2.15,3.00,3.40,2.07,3.00,3.40,2.15,2.87,3.30,2.10,2.90,3.30,2.15,2.90,3.30,2.15,3.15,3.44,2.19,3.15,3.50,2.20,3.00,3.37,2.12,3.10,3.55,2.24,1.80,2.00,1.78,2.00,1.80,2.00,1.73,1.98,1.76,2.00,0.25,1.90,1.90,1.90,1.90,1.90,1.90,1.85,1.85,NaN,NaN,3.60,3.60,1.95,3.50,3.50,1.95,3.00,3.45,2.05,3.10,3.40,2.10,3.20,3.40,1.95,3.10,3.40,2.00,2.90,3.30,2.15,3.20,3.50,2.22,3.60,3.60,2.15,3.20,3.44,2.02,3.55,3.80,2.12,1.75,2.05,1.78,2.00,1.75,2.05,1.72,1.99,1.80,2.12,0.50,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12,EC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,EC,11/04/2026,15:00,Scunthorpe,Brackley Town,1,0,H,1,0,H,I Searle,1,3,0,0,1.42,4.20,6.50,1.40,4.33,6.50,1.42,4.40,5.80,1.40,4.40,6.50,1.42,4.33,5.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.48,4.50,6.50,1.42,4.29,6.23,1.46,4.50,6.80,1.60,2.30,NaN,NaN,1.62,2.30,1.59,2.22,1.20,1.15,-1.25,1.98,1.83,NaN,NaN,1.98,1.83,1.93,1.77,1.99,1.74,1.48,4.00,5.75,1.44,4.33,6.00,1.42,4.40,5.80,1.45,4.20,6.00,1.46,4.20,5.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.54,4.50,6.50,1.45,4.25,5.68,1.60,4.60,5.70,1.60,2.30,NaN,NaN,1.60,2.38,1.57,2.27,1.64,2.48,-1.00,1.78,2.03,NaN,NaN,1.81,2.03,1.76,1.93,1.95,1.97,EC
520,EC,11/04/2026,15:00,Southend,Solihull,0,0,D,0,0,D,A Bannister,2,2,0,0,1.42,4.33,6.50,1.40,4.50,6.50,1.44,4.35,5.75,1.40,4.40,6.50,1.41,4.40,5.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,4.75,6.50,1.41,4.41,6.02,1.49,1.03,1.04,1.57,2.35,NaN,NaN,1.57,2.45,1.53,2.34,1.17,1.08,-1.25,1.93,1.88,NaN,NaN,1.93,1.88,1.88,1.81,1.01,1.01,1.40,4.33,7.00,1.40,4.33,6.50,1.44,4.35,5.75,1.40,4.40,6.50,1.42,4.33,5.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,4.75,7.25,1.42,4.37,6.16,1.48,4.90,7.20,1.62,2.25,NaN,NaN,1.62,2.45,1.56,2.29,1.63,2.46,-1.25,1.93,1.88,NaN,NaN,1.93,1.88,1.88,1.81,1.98,1.90,EC
521,EC,11/04/2026,15:00,Woking,Morecambe,5,1,H,2,1,H,K Dowle,3,0,0,0,1.75,3.80,3.75,1.73,3.75,4.00,1.83,3.65,3.60,1.73,3.80,4.00,1.70,3.70,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.83,4.00,4.00,1.74,3.77,3.85,1.78,3.95,4.00,1.60,2.30,NaN,NaN,1.60,2.38,1.57,2.26,1.60,2.38,-0.75,1.98,1.83,NaN,NaN,1.98,1.83,1.91,1.78,1.94,1.75,1.83,3.90,3.40,1.80,4.00,3.60,1.83,3.65,3.60,1.80,3.80,3.60,1.75,3.70,3.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.87,4.00,4.00,1.80,3.83,3.55,1.97,4.40,3.65,1.50,2.50,NaN,NaN,1.57,2.50,1.52,2.38,1.56,2.62,-0.50,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,1.97,2.00,EC
522,EC,11/04/2026,15:00,Yeovil,Halifax,0,0,D,0,0,D,R Massey-Ellis,1,3,0,0,3.20,3.40,2.00,3.30,3.30,2.05,3.00,3.25,2.18,3.30,3.25,2.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.30,3.60,2.18,3.20,3.31,2.06,3.60,2.98,2.08,2.00,1.80,NaN,NaN,2.00,1.86,1.96,1.77,1.71,1.64,0.25,2.03,1.78,NaN,NaN,2.03,1.78,1.94,1.75,2.02,1.80,3.30,3.30,2.00,3.50,3.25,2.00,3.25,3.15,2.10,3.70,3.30,1.93,3.40,3.20,1.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.70,3.40,2.10,3.39,3.25,2.02,3.85,3.55,2.14,2.08,1.73,NaN,NaN,2.10,1.75,2.03,1.71,2.16,1.78,0.50,1.80,2.00,NaN,NaN,1.80,2.05,1.73,1.96,1.80,2.14,EC
523,EC,11/04/2026,17:30,Rochdale,Wealdstone,2,1,H,0,0,D,J Miles,2,1,0,0,1.30,4.75,9.00,1.30,5.00,8.00,1.27,5.10,8.50,1.30,4.80,8.50,1.32,4.75,7.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.36,5.10,9.00,1.31,4.79,8.08,1.34,5.30,8.40,1.62,2.25,NaN,NaN,1.62,2.32,1.58,2.25,1.64,2.32,-1.50,1.95,1.85,NaN,NaN,1.95,1.85,1.89,1.78,1.95,1.78,1.30,4.75,9.00,1.30,4.60,9.00,1.27,5.10,9.00,1.29,4.80,9.00,1.30,4.80,7.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.36,5.33,9.60,1.30,4.85,8.35,1.33,5.80,10.50,1.60,2.30,NaN,NaN,1.65,2.30,1.58,2.23,1.64,2.44,-1.50,1.90,1.90,NaN,NaN,1.90,1.90,1.86,1.82,2.00,1.90,EC

### Multiple Seasons

In [13]:
for season in range(20, 26):
    print(str(season) + str(season+1))

2021
2122
2223
2324
2425
2526

In [14]:
# creating a list of leagues and seasons (multi-season load)
# NOTE: frame_list is appended in outer-loop (league) then inner-loop (season).
# Order mapping: index = (league_index * n_seasons) + season_index
#   e.g. with 3 leagues and 5 seasons: indices 0-4 -> league0 seasons, 5-9 -> league1 seasons, etc.
leagues = ["E0", "E1", "E2"]
frame_list = []  # create an empty list to store the dataframes

root = "https://www.football-data.co.uk/mmz4281/"
seasons = [f"{s}{s+1}" for s in range(21, 26)]  # ['2122','2223','2324','2425','2526']

for league in leagues:
    for season_code in seasons:
        url = root + season_code + "/" + league + ".csv"
        try:
            df = pd.read_csv(url)
        except Exception as e:
            print(f"✗ Skipped: {url}  →  {e}")
            continue
        # label each frame so callers can select by League+Season reliably
        df = df.assign(League=league, Season=season_code)
        frame_list.append(df)
        print(f"✓ Loaded: {league} {season_code}")

# After loading, recommended access patterns:
# 1) By numeric index (if you know the order):
#      league_idx = 1  # index of 'E1' in `leagues`
#      season_idx = 2  # index of desired season in `seasons`
#      idx = league_idx * len(seasons) + season_idx
#      frame = frame_list[idx]
# 2) Prefer explicit lookup by (league,season):
#      frames_by_key = {(f['League'].iat[0], f['Season'].iat[0]): f for f in frame_list}
#      frames_by_key[('E1','2223')]
# 3) Or filter the combined DataFrame:
#      combined = pd.concat(frame_list, ignore_index=True)
#      combined[(combined['League']=='E1') & (combined['Season']=='2223')]

# Build combined and de-fragment for downstream work
if frame_list:
    combined = pd.concat(frame_list, ignore_index=True).copy()
    print(f"Loaded {len(frame_list)} frames; combined shape: {combined.shape}")
else:
    print("No frames loaded.")

✓ Loaded: E0 2122
✓ Loaded: E0 2223
✓ Loaded: E0 2324

C:\Users\steph\AppData\Local\Temp\ipykernel_33908\3194263412.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(League=league, Season=season_code)

✓ Loaded: E0 2425
✓ Loaded: E0 2526
✓ Loaded: E1 2122
✓ Loaded: E1 2223
✓ Loaded: E1 2324
✓ Loaded: E1 2425
✓ Loaded: E1 2526
✓ Loaded: E2 2122
✓ Loaded: E2 2223
✓ Loaded: E2 2324
✓ Loaded: E2 2425
✓ Loaded: E2 2526
Loaded 15 frames; combined shape: (7255, 164)

In [15]:
# length of frames
len(frame_list)

15

In [16]:
# show the 1st, 2nd, or 4th ,   15th dataframe in the list
frame_list[0]  # 1st dataframe]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,League,Season
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,H,M Oliver,8,22,3,4,12,8,2,5,0,0,0,0,4.00,3.40,1.95,4.00,3.50,1.95,3.80,3.40,2.05,4.05,3.46,2.05,4.00,3.40,1.90,4.10,3.40,2.00,4.62,3.72,2.10,4.02,3.43,2.02,2.10,1.72,2.22,1.73,2.26,1.83,2.16,1.73,0.50,1.86,2.07,1.88,2.06,2.05,2.08,1.87,2.03,3.80,3.25,2.05,3.80,3.30,2.05,3.80,3.25,2.10,3.94,3.33,2.13,3.90,3.00,2.05,3.90,3.25,2.10,4.20,3.50,2.18,3.89,3.28,2.10,2.37,1.57,2.44,1.62,2.47,1.75,2.33,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09,E0,2122
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,H,P Tierney,16,10,8,3,11,9,5,4,1,2,0,0,1.53,4.50,5.75,1.53,4.50,5.75,1.55,4.40,5.75,1.56,4.57,5.96,1.52,4.33,5.80,1.55,4.40,6.00,1.59,4.65,6.35,1.55,4.48,5.87,1.61,2.30,1.67,2.32,1.71,2.38,1.65,2.29,-1.00,1.95,1.98,1.96,1.96,2.00,2.01,1.93,1.96,1.61,4.20,5.25,1.62,4.10,5.25,1.65,4.20,4.90,1.67,4.20,5.40,1.57,4.20,5.50,1.65,4.10,5.25,1.71,4.33,5.80,1.64,4.19,5.22,1.66,2.20,1.70,2.27,1.75,2.37,1.67,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79,E0,2122
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,H,D Coote,14,14,3,8,10,7,7,6,2,1,0,0,3.10,3.10,2.45,3.20,3.10,2.40,3.15,3.05,2.45,3.30,3.12,2.51,3.20,3.00,2.45,3.13,3.10,2.45,3.33,3.20,2.60,3.19,3.09,2.49,2.50,1.53,2.56,1.56,2.56,1.63,2.46,1.57,0.25,1.80,2.14,1.83,2.12,1.83,2.17,1.79,2.12,3.10,3.10,2.45,3.25,3.10,2.40,3.10,3.05,2.45,3.27,3.14,2.51,3.10,3.00,2.45,3.13,3.13,2.50,3.35,3.20,2.56,3.19,3.10,2.48,2.30,1.61,2.33,1.67,2.42,1.71,2.34,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12,E0,2122
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,H,J Moss,13,4,6,1,15,11,5,2,0,0,0,0,1.25,5.75,13.00,1.28,5.75,10.50,1.25,6.00,13.00,1.26,6.24,12.74,1.25,5.50,13.00,1.25,5.75,13.00,1.30,6.30,15.00,1.26,5.92,12.80,1.80,2.00,1.80,2.09,1.84,2.12,1.79,2.06,-1.50,1.84,2.09,1.79,2.12,1.93,2.12,1.83,2.07,1.30,5.25,11.00,1.33,5.00,10.00,1.30,5.25,11.00,1.34,5.40,11.00,1.30,5.25,10.00,1.33,5.00,11.00,1.36,5.50,11.50,1.33,5.17,10.58,1.90,1.90,1.93,1.98,1.96,2.07,1.90,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82,E0,2122
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,A,A Madley,14,6,6,3,13,15,6,8,2,0,0,0,1.90,3.50,4.00,1.95,3.50,3.90,1.95,3.45,3.95,2.01,3.56,4.10,1.95,3.40,4.00,1.95,3.40,4.10,2.04,3.66,4.25,1.97,3.53,4.04,2.00,1.80,2.14,1.78,2.14,1.85,2.07,1.79,-0.50,2.00,1.93,2.01,1.92,2.01,1.97,1.96,1.92,2.00,3.40,3.90,2.05,3.40,3.75,2.00,3.35,4.00,2.05,3.45,4.07,1.95,3.40,3.90,2.00,3.30,4.20,2.12,3.50,4.20,2.04,3.39,3.95,2.20,1.66,2.28,1.69,2.34,1.77,2.24,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86,E0,2122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,H,M Atkinson,6,10,3,4,12,22,3,6,2,4,0,0,3.00,3.60,2.25,3.00,3.50,2.25,3.15,3.55,2.20,3.15,3.79,2.24,3.00,3.50,2.25,3.00,3.50,2.20,3.23,3.81,2.35,3.10,3.66,2.25,1.72,2.10,1.76,2.15,1.80,2.19,1.74,2.12,0.25,1.92,1.98,1.95,1.95,1.96,2.02,1.91,1.95,2.70,3.50,2.50,2.75,3.40,2.45,2.95,3.45,2.40,2.82,3.57,2.59,2.80,3.40,2.45,2.80,3.50,2.50,3.01,3.65,2.64,2.81,3.49,2.53,1.80,2.00,1.83,2.08,1.84,2.17,1.80,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16,E0,2122
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,D,J Moss,12,7,6,2,10,5,3,3,0,1,0,0,1.85,4.00,3.80,1.85,3.90,3.80,1.85,3.95,3.80,1.88,4.13,3.91,1.88,3.80,3.75,1.83,3.80,3.80,1.95,4.25,4.00,1.88,4.03,3.86,1.57,2.37,1.63,2.39,1.66,2.52,1.58,2.39,-0.50,1.87,2.03,1.88,2.03,1.90,2.05,1.87,2.01,1.65,4.33,4.50,1.71,4.10,4.40,1.73,4.20,4.30,1.70,4.39,4.67,1.70,4.00,4.50,1.70,4.20,4.80,1.77,4.45,4.80,1.71,4.29,4.52,1.50,2.62,1.51,2.67,1.53,2.85,1.49,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01,E0,2122
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,D,A Taylor,29,7,8,5,6,3,5,3,1,0,0,0,1.14,8.50,15.00,1.16,7.75,15.00,1.17,7.75,16.00,1.15,8.49,21.36,1.15,7.00,19.00,1.13,8.00,19.00,1.19,8.80,23.00,1.16,8.12,18.95,1.44,2.75,1.43,2.89,1.51,3.02,1.43,2.82,-2.00,1.73,2.08,1.77,2.14,1.87,2.16,1.78,2.11,1.12,9.00,17.00,1.13,8.75,16.50,1.15,8.00,17.00,1.14,9.75,19.00,1.12,8.00,21.00,1.14,8.50,20.00,1.17,10.90,24.00,1.14,9.22,19.12,1.33,3.40,1.34,3.43,1.39,3.48,1.34,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80,E0,2122
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,A,M Oliver,24,4,5,2,5,11,13,1,0,1,0,0,1.16,8.00,17.00,1.17,8.00,15.00,1.15,7.50,18.00,1.15,8.74,20.27,1.15,7.00,19.00,1.13,7.50,18.00,1.20,9.10,24.00,1.16,8.18,18.24,1.44,2.75,1.43,2.93,1.48,2.98,1.43,2.81,-2.00,1.84,2.06,1.79,2.11,1.89,2.14,1.82,2.07,1.18,7.50,13.00,1.18,8.00,14.00,1.15,8.00,17.00,1.17,8.40,17.00,1.17,7.50,15.00,1.18,8.00,15.00,1.20,8.80,19.00,1.17,8.27,15.87,1.30,3.50,1.34,3.41,1.37,3.70,1.33,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87,E0,2122
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,A,C Kavanagh,9,19,0,13,13,7,3,2,3,1,0,0,9.50,6.50,1.25,11.00,6.50,1.24,11.00,6.25,1.25,11.20,6.23,1.27,10.00,6.00,1.25,11.50,6.00,1.22,13.00,7.00,1.29,11.19,6.45,1.26,1.44,2.75,1.45,2.82,1.51,2.94,1.44,2.79,1.75,1.99,1.91,1.99,1.90,2.04,1.95,1.97,1.90,8.50,5.25,1.33,9.50,5.50,1.31,12.00,6.25,1.25,9.82,5.51,1.34,9.50,5.25,1.32,10.00,5.25,1.33,12.00,6.25,1.36,9.99,5.59,1.31,1.61,2.30,1.63,2.37,1.63,2.58,1.58,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89,E0,2122

In [17]:
# De-fragment existing frames to avoid PerformanceWarning
# This copies each DataFrame to a new contiguous block of memory.
try:
    for i, f in enumerate(frame_list):
        frame_list[i] = f.copy()
    print(f"De-fragmented {len(frame_list)} frames")
except NameError:
    print("frame_list not defined; nothing to de-fragment")

# If a combined DataFrame exists, copy it too to ensure it's de-fragmented
if 'combined' in globals():
    combined = combined.copy()
    print(f"Refreshed combined DataFrame: {combined.shape}")

De-fragmented 15 frames
Refreshed combined DataFrame: (7255, 164)

## Organise all the data in a dictionary

In [18]:
# create a dictionary with original name of league as key

league_dict = {
    "Premier League": "PL",
    "La Liga": "LL",
    "Serie A": "SA",
    "Bundesliga": "BL",
    "Ligue 1": "L1"
}

In [19]:
# get a dictionary element by key
league_dict["Premier League"]

'PL'

In [20]:
# looping through the dictionary and printing the key and value
for key, value in league_dict.items():
    print(f"{key} -> {value}")

Premier League -> PL
La Liga -> LL
Serie A -> SA
Bundesliga -> BL
Ligue 1 -> L1

In [21]:
historic_dict = {}
league_dict = {
    "Premier League": "E0",
    "La Liga": "E1",
    "Serie A": "E2",
    "Bundesliga": "E3",
    "Ligue 1": "E4"
}


  

for league_name, league_code in league_dict.items():
    frame_list = []  # create an empty list to store the dataframes for each league
    
    for season in range(20, 26):
        url = root + str(season) + str(season+1) + "/" + league_code + ".csv"
        try:                            # try-except block to handle potential errors in reading the CSV file
            df = pd.read_csv(url)       # attempt to read the CSV file from the URL and store it in a dataframe
        except Exception as e:          # if an error occurs, print a message and skip to the next iteration
            print(f"✗ Skipped: {url}  →  {e}")
            continue                    # skip to the next iteration of the loop if an error occurs
         
         # label each frame so callers can select by League+Season reliably 
        df = df.assign(League=league, Season=f"{season}{season+1}")
        frame_list.append(df)
        if frame_list:  # check if any frames were loaded for the league
            print(f"✓ Loaded: {league_name} {season}{season+1}")
        historic_dict[league] = pd.concat(frame_list, ignore_index=True)

✓ Loaded: Premier League 2021
✓ Loaded: Premier League 2122
✓ Loaded: Premier League 2223
✓ Loaded: Premier League 2324

C:\Users\steph\AppData\Local\Temp\ipykernel_33908\2265442956.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(League=league, Season=f"{season}{season+1}")

✓ Loaded: Premier League 2425
✓ Loaded: Premier League 2526
✓ Loaded: La Liga 2021
✓ Loaded: La Liga 2122
✓ Loaded: La Liga 2223
✓ Loaded: La Liga 2324
✓ Loaded: La Liga 2425
✓ Loaded: La Liga 2526
✓ Loaded: Serie A 2021
✓ Loaded: Serie A 2122
✓ Loaded: Serie A 2223
✓ Loaded: Serie A 2324
✓ Loaded: Serie A 2425
✓ Loaded: Serie A 2526
✓ Loaded: Bundesliga 2021
✓ Loaded: Bundesliga 2122
✓ Loaded: Bundesliga 2223
✓ Loaded: Bundesliga 2324
✓ Loaded: Bundesliga 2425
✓ Loaded: Bundesliga 2526
✗ Skipped: https://www.football-data.co.uk/mmz4281/2021/E4.csv  →  HTTP Error 300: Multiple Choices
✗ Skipped: https://www.football-data.co.uk/mmz4281/2122/E4.csv  →  HTTP Error 300: Multiple Choices
✗ Skipped: https://www.football-data.co.uk/mmz4281/2223/E4.csv  →  HTTP Error 300: Multiple Choices
✗ Skipped: https://www.football-data.co.uk/mmz4281/2324/E4.csv  →  HTTP Error 300: Multiple Choices
✗ Skipped: https://www.football-data.co.uk/mmz4281/2425/E4.csv  →  HTTP Error 300: Multiple Choices
✗ Skipped: https://www.football-data.co.uk/mmz4281/2526/E4.csv  →  HTTP Error 300: Multiple Choices

In [22]:
print(list(historic_dict.keys()))

['E2']

In [23]:
historic_dict.get("premier_league")            # returns None if missing
historic_dict.get("premier_league", "missing") # custom default

'missing'

In [24]:
# show dataframe  inside the historic_dict dictionary
historic_dict.keys()

dict_keys(['E2'])